import legacy from "./legacy.json";

/**
 * Old site URL → new path (plan §5.4). Generated by the CT seed's redirects step (do not edit by
 * hand): keys are lowercased paths without a trailing slash, values are unprefixed new paths.
 */
const LEGACY_REDIRECTS: Record<string, string> = legacy;

export function lookupLegacyRedirect(pathname: string): string | undefined {
  let decoded = pathname;
  try {
    decoded = decodeURIComponent(pathname);
  } catch {
    // keep the raw path
  }
  const key = decoded.toLowerCase().replace(/\/+$/u, "") || "/";
  return LEGACY_REDIRECTS[key];
}
