import { downloadTemplate } from "giget";
import {
  copyFile,
  mkdir,
  readdir,
  readFile,
  readlink,
  rm,
  symlink,
  writeFile,
} from "node:fs/promises";
import { join } from "node:path";

export type TemplateSource = { kind: "github"; ref: string } | { kind: "local"; path: string };

/** Maps published package name -> version, harvested from the template before pruning. */
export type PluginVersions = Record<string, string>;

// Every `packages/<PLUGIN_DIR_PREFIX>*` directory is pruned: users consume the
// plugins as published npm packages instead of workspace source. Matching by
// prefix rather than an explicit list means a newly added plugin can never be
// forgotten here and leak into scaffolded projects.
const PLUGIN_DIR_PREFIX = "payload-plugin-";

// `apps/cms` is the only app a scaffolded project gets. Everything else under
// `apps/` is a source-monorepo sandbox or demo (`dev`, `multi-tenancy-demo`, …)
// and is pruned by exclusion, so new sandboxes can't leak into output either.
const KEPT_APP = "cms";

const PRUNE_PATHS = [
  // The CLI itself — its source lives inside the monorepo and must not bleed into scaffolded projects.
  "packages/create-ideal-cms",
  // Release machinery — not relevant downstream.
  ".releaserc.json",
  ".github",
  // Internal repo bookkeeping.
  "skills-lock.json",
  "docs",
  "CLAUDE.md",
  ".cursor",
  // Agent config: repo-specific skills/subagents, plus `.claude/worktrees/`,
  // which holds entire extra checkouts of this monorepo.
  ".claude",
  ".agents",
  // Lockfile gets regenerated by the user's package manager.
  "bun.lock",
  // Any caches / build artifacts that may have slipped through.
  ".turbo",
  "apps/cms/.turbo",
  "apps/cms/.next",
  "apps/cms/.env",
  "apps/cms/test.env",
] as const;

// When copying from a local source repo we skip these at any depth to avoid
// dragging huge generated trees and the upstream .git history. `.test-output`
// is here so `bun run test:local` (which scaffolds INTO that dir) can still
// use the monorepo itself as the source without infinite recursion.
const LOCAL_COPY_SKIP = new Set([
  "node_modules",
  ".next",
  ".turbo",
  "dist",
  ".git",
  ".DS_Store",
  ".test-output",
  // Pruned anyway, but skipped up front so `.claude/worktrees/` — which can hold
  // several full checkouts of this monorepo — is never copied in the first place.
  ".claude",
  ".agents",
]);

const MIGRATION_STUB = `// Regenerated by create-ideal-cms.
// Run \`<pm> run payload migrate:create init\` to populate this index.
export const migrations: { up: () => Promise<void>; down: () => Promise<void>; name: string }[] = []
`;

// Manual recursive copy. Replaces `fs.cp` because that errors with EINVAL when
// `dest` is a subdirectory of `src` — which is exactly what `bun run test:local`
// does (scaffolds into `.test-output` inside the source monorepo).
async function copyLocal(src: string, dest: string): Promise<void> {
  await mkdir(dest, { recursive: true });
  const entries = await readdir(src, { withFileTypes: true });
  await Promise.all(
    entries.map(async (entry) => {
      if (LOCAL_COPY_SKIP.has(entry.name)) return;
      const sp = join(src, entry.name);
      const dp = join(dest, entry.name);
      if (entry.isSymbolicLink()) {
        const target = await readlink(sp);
        await symlink(target, dp);
      } else if (entry.isDirectory()) {
        await copyLocal(sp, dp);
      } else if (entry.isFile()) {
        await copyFile(sp, dp);
      }
    })
  );
}

async function resetMigrations(targetDir: string): Promise<void> {
  const dir = join(targetDir, "apps/cms/src/database/migrations");
  let entries: string[];
  try {
    entries = await readdir(dir);
  } catch {
    return;
  }
  await Promise.all(
    entries
      .filter((e) => e !== "index.ts")
      .map((e) => rm(join(dir, e), { recursive: true, force: true }))
  );
  await writeFile(join(dir, "index.ts"), MIGRATION_STUB);
}

/**
 * Lists `packages/payload-plugin-*` dirs and reads each one's published name +
 * version. Must run BEFORE the prune — the versions are the only reason those
 * directories are fetched at all. Dirs without a readable `package.json` (stray
 * build artifacts) contribute nothing but are still returned for pruning.
 */
async function collectPluginPackages(
  targetDir: string
): Promise<{ dirs: string[]; versions: PluginVersions }> {
  const packagesDir = join(targetDir, "packages");
  let entries: string[];
  try {
    entries = (await readdir(packagesDir, { withFileTypes: true }))
      .filter((e) => e.isDirectory() && e.name.startsWith(PLUGIN_DIR_PREFIX))
      .map((e) => e.name);
  } catch {
    return { dirs: [], versions: {} };
  }

  const versions: PluginVersions = {};
  await Promise.all(
    entries.map(async (name) => {
      try {
        const pkg = JSON.parse(
          await readFile(join(packagesDir, name, "package.json"), "utf-8")
        ) as { name?: string; version?: string; private?: boolean };
        if (pkg.name && pkg.version && pkg.private !== true) versions[pkg.name] = pkg.version;
      } catch {
        // No package.json / unparsable — not a real workspace package, prune only.
      }
    })
  );

  return { dirs: entries.map((name) => join("packages", name)), versions };
}

/** Every `apps/*` dir except the one app a scaffolded project keeps. */
async function collectExtraAppDirs(targetDir: string): Promise<string[]> {
  try {
    return (await readdir(join(targetDir, "apps"), { withFileTypes: true }))
      .filter((e) => e.isDirectory() && e.name !== KEPT_APP)
      .map((e) => join("apps", e.name));
  } catch {
    return [];
  }
}

export async function fetchTemplate(
  targetDir: string,
  source: TemplateSource
): Promise<PluginVersions> {
  if (source.kind === "local") {
    await copyLocal(source.path, targetDir);
  } else {
    await downloadTemplate(`gh:focusreactive/payload-plugins#${source.ref}`, {
      dir: targetDir,
      force: false,
      preferOffline: false,
      install: false,
    });
  }

  const [{ dirs, versions }, extraApps] = await Promise.all([
    collectPluginPackages(targetDir),
    collectExtraAppDirs(targetDir),
  ]);

  await Promise.all(
    [...PRUNE_PATHS, ...dirs, ...extraApps].map((path) =>
      rm(join(targetDir, path), { recursive: true, force: true })
    )
  );

  await resetMigrations(targetDir);

  return versions;
}
