import { downloadTemplate } from "giget";
import { copyFile, mkdir, readdir, readlink, rm, symlink, writeFile } from "node:fs/promises";
import { join } from "node:path";

export type TemplateSource = { kind: "github"; ref: string } | { kind: "local"; path: string };

const PRUNE_PATHS = [
  // Plugin source — users consume them as published npm packages instead.
  "packages/payload-plugin-ab",
  "packages/payload-plugin-comments",
  "packages/payload-plugin-presets",
  "packages/payload-plugin-scheduling",
  "packages/payload-plugin-translator",
  // The CLI itself — its source lives inside the monorepo and must not bleed into scaffolded projects.
  "packages/create-ideal-cms",
  // The plugin dev sandbox app — only useful inside the source monorepo.
  "apps/dev",
  // Release machinery — not relevant downstream.
  ".releaserc.json",
  ".github",
  // Internal repo bookkeeping.
  "skills-lock.json",
  "docs",
  "CLAUDE.md",
  ".cursor",
  // Lockfile gets regenerated by the user's package manager.
  "bun.lock",
  // Any caches / build artifacts that may have slipped through.
  ".turbo",
  "apps/cms/.turbo",
  "apps/cms/.next",
  "apps/cms/.env",
  "apps/cms/test.env",
] as const;

// When copying from a local source repo we skip these at any depth to avoid
// dragging huge generated trees and the upstream .git history. `.test-output`
// is here so `bun run test:local` (which scaffolds INTO that dir) can still
// use the monorepo itself as the source without infinite recursion.
const LOCAL_COPY_SKIP = new Set(["node_modules", ".next", ".turbo", "dist", ".git", ".DS_Store", ".test-output"]);

const MIGRATION_STUB = `// Regenerated by create-ideal-cms.
// Run \`<pm> run payload migrate:create init\` to populate this index.
export const migrations: { up: () => Promise<void>; down: () => Promise<void>; name: string }[] = []
`;

// Manual recursive copy. Replaces `fs.cp` because that errors with EINVAL when
// `dest` is a subdirectory of `src` — which is exactly what `bun run test:local`
// does (scaffolds into `.test-output` inside the source monorepo).
async function copyLocal(src: string, dest: string): Promise<void> {
  await mkdir(dest, { recursive: true });
  const entries = await readdir(src, { withFileTypes: true });
  await Promise.all(
    entries.map(async (entry) => {
      if (LOCAL_COPY_SKIP.has(entry.name)) return;
      const sp = join(src, entry.name);
      const dp = join(dest, entry.name);
      if (entry.isSymbolicLink()) {
        const target = await readlink(sp);
        await symlink(target, dp);
      } else if (entry.isDirectory()) {
        await copyLocal(sp, dp);
      } else if (entry.isFile()) {
        await copyFile(sp, dp);
      }
    })
  );
}

async function resetMigrations(targetDir: string): Promise<void> {
  const dir = join(targetDir, "apps/cms/src/database/migrations");
  let entries: string[];
  try {
    entries = await readdir(dir);
  } catch {
    return;
  }
  await Promise.all(entries.filter((e) => e !== "index.ts").map((e) => rm(join(dir, e), { recursive: true, force: true })));
  await writeFile(join(dir, "index.ts"), MIGRATION_STUB);
}

export async function fetchTemplate(targetDir: string, source: TemplateSource): Promise<void> {
  if (source.kind === "local") {
    await copyLocal(source.path, targetDir);
  } else {
    await downloadTemplate(`gh:focusreactive/payload-plugins#${source.ref}`, {
      dir: targetDir,
      force: false,
      preferOffline: false,
      install: false,
    });
  }

  await Promise.all(PRUNE_PATHS.map((path) => rm(join(targetDir, path), { recursive: true, force: true })));

  await resetMigrations(targetDir);
}
