import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { Answers } from "./prompts.js";
import type { PluginVersions } from "./scaffold.js";
import { PRIVATE_PLUGIN_STUBS, PRIVATE_SCOPE_LINE_FILES, STRIPPED_DEP_SCOPE } from "./stubs.js";

// Workspace packages that survive the prune and stay as `workspace:*` in the
// scaffolded monorepo. Anything else still on `workspace:*` after the rewrite
// points at source we deleted, so it's a hard error rather than a broken install.
const KEPT_WORKSPACE_PREFIX = "@repo/";

type Pkg = Record<string, unknown> & {
  name?: string;
  scripts?: Record<string, string>;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
};

async function readJson<T>(file: string): Promise<T> {
  return JSON.parse(await readFile(file, "utf-8")) as T;
}

async function writeJson(file: string, data: unknown): Promise<void> {
  await writeFile(file, `${JSON.stringify(data, null, 2)}\n`);
}

function rewritePluginRefs(
  deps: Record<string, string> | undefined,
  versions: PluginVersions
): string[] {
  if (!deps) return [];
  const unresolved: string[] = [];
  for (const [name, range] of Object.entries(deps)) {
    if (!range.startsWith("workspace:")) continue;
    const version = versions[name];
    if (version) {
      // Pinned exactly, matching the source monorepo's exact-version style.
      deps[name] = version;
    } else if (!name.startsWith(KEPT_WORKSPACE_PREFIX)) {
      unresolved.push(name);
    }
  }
  return unresolved;
}

async function transformRootPackageJson(targetDir: string, answers: Answers): Promise<void> {
  const file = join(targetDir, "package.json");
  const pkg = await readJson<Pkg>(file);

  pkg.name = answers.projectName;

  if (pkg.scripts) {
    delete pkg.scripts.release;
    // Source's prepare runs `lefthook install`, which fails without a git repo
    // and crashes downstream `bun install`. Users opt in by running `lefthook install`.
    delete pkg.scripts.prepare;
  }
  if (pkg.devDependencies) {
    for (const dep of Object.keys(pkg.devDependencies)) {
      if (dep.startsWith("@semantic-release/") || dep === "multi-semantic-release") {
        // oxlint-disable-next-line typescript/no-dynamic-delete
        delete pkg.devDependencies[dep];
      }
    }
  }

  await writeJson(file, pkg);
}

function dropPrivateScopeDeps(deps: Record<string, string> | undefined): void {
  if (!deps) return;
  for (const name of Object.keys(deps)) {
    if (name.startsWith(STRIPPED_DEP_SCOPE)) {
      // oxlint-disable-next-line typescript/no-dynamic-delete
      delete deps[name];
    }
  }
}

/**
 * Removes the private-scope plugins a scaffolded project cannot install:
 * their deps, their wiring (via whole-file stubs), and their lines in
 * generated / documentation files.
 */
async function stripPrivateScopePlugins(targetDir: string): Promise<void> {
  await Promise.all(
    Object.entries(PRIVATE_PLUGIN_STUBS).map(([path, contents]) =>
      writeFile(join(targetDir, path), contents)
    )
  );

  await Promise.all(
    PRIVATE_SCOPE_LINE_FILES.map(async (path) => {
      const file = join(targetDir, path);
      let contents: string;
      try {
        contents = await readFile(file, "utf-8");
      } catch {
        return;
      }
      const kept = contents.split("\n").filter((line) => !line.includes(STRIPPED_DEP_SCOPE));
      await writeFile(file, kept.join("\n"));
    })
  );
}

async function transformCmsPackageJson(
  targetDir: string,
  pluginVersions: PluginVersions
): Promise<void> {
  const file = join(targetDir, "apps/cms/package.json");
  const pkg = await readJson<Pkg>(file);
  dropPrivateScopeDeps(pkg.dependencies);
  dropPrivateScopeDeps(pkg.devDependencies);
  const unresolved = [
    ...rewritePluginRefs(pkg.dependencies, pluginVersions),
    ...rewritePluginRefs(pkg.devDependencies, pluginVersions),
  ];
  if (unresolved.length > 0) {
    throw new Error(
      `apps/cms/package.json still depends on pruned workspace packages with no published version: ${unresolved.join(", ")}`
    );
  }
  await writeJson(file, pkg);
}

function escapeEnvValue(value: string): string {
  if (value === "") return "";
  return `'${value.replace(/'/gu, "'\\''")}'`;
}

function envLine(key: string, value: string, optional = false): string {
  if (optional && value === "") return `# ${key}=`;
  return `${key}=${escapeEnvValue(value)}`;
}

async function writeEnvFile(targetDir: string, answers: Answers): Promise<void> {
  const lines = [
    "# Generated by create-ideal-cms",
    envLine("DATABASE_URL", answers.databaseUrl),
    envLine("PAYLOAD_SECRET", answers.payloadSecret),
    envLine("NEXT_PUBLIC_SERVER_URL", answers.publicServerUrl),
    "",
    "# Used to validate preview requests",
    envLine("PREVIEW_SECRET", answers.payloadSecret.slice(0, 32)),
    "",
    "# Vercel Blob Storage (for media uploads)",
    envLine("BLOB_READ_WRITE_TOKEN", answers.blobToken, true),
    "",
    "# AI SEO + translator. The translator plugin instantiates OpenAI at config-load,",
    "# so a non-empty value is required for payload to boot. Replace with a real key",
    "# from https://platform.openai.com/api-keys to actually use these features.",
    envLine("OPENAI_API_KEY", answers.openaiApiKey || "sk-placeholder-replace-with-real-key"),
    "",
    "# OIDC SSO (optional)",
    envLine("OIDC_ISSUER", answers.oidcIssuer, true),
    envLine("OIDC_CLIENT_ID", answers.oidcClientId, true),
    envLine("OIDC_CLIENT_SECRET", answers.oidcClientSecret, true),
    "",
  ];
  await writeFile(join(targetDir, "apps/cms/.env"), `${lines.join("\n")}\n`);
}

async function overrideThemeColor(targetDir: string, hex: string): Promise<void> {
  const file = join(targetDir, "packages/tailwind-config/base.css");
  const css = await readFile(file, "utf-8");
  const overlay = `
/* create-ideal-cms: brand color overlay */
@theme {
  --color-primary: ${hex};
}
`;
  await writeFile(file, `${css.trimEnd()}\n${overlay}`);
}

export async function applyTransforms(
  answers: Answers,
  pluginVersions: PluginVersions
): Promise<void> {
  await transformRootPackageJson(answers.targetDir, answers);
  await transformCmsPackageJson(answers.targetDir, pluginVersions);
  await stripPrivateScopePlugins(answers.targetDir);
  await writeEnvFile(answers.targetDir, answers);
  await overrideThemeColor(answers.targetDir, answers.primaryColor);
}
