import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { Answers } from "./prompts.js";

// Plugins that ship as `workspace:*` in the source monorepo and need a real
// version range in the scaffold output. Pinned exactly to match the source's
// "exact-version" style. Bump when a new plugin version ships.
const PLUGIN_VERSIONS: Record<string, string> = {
  "@focus-reactive/payload-plugin-ab": "2.6.0",
  "@focus-reactive/payload-plugin-comments": "1.8.0",
  "@focus-reactive/payload-plugin-presets": "0.11.0",
  "@focus-reactive/payload-plugin-scheduling": "1.2.0",
  "@focus-reactive/payload-plugin-translator": "0.2.0",
};

type Pkg = Record<string, unknown> & {
  name?: string;
  scripts?: Record<string, string>;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
};

async function readJson<T>(file: string): Promise<T> {
  return JSON.parse(await readFile(file, "utf-8")) as T;
}

async function writeJson(file: string, data: unknown): Promise<void> {
  await writeFile(file, `${JSON.stringify(data, null, 2)}\n`);
}

function rewritePluginRefs(deps: Record<string, string> | undefined): void {
  if (!deps) return;
  for (const [name, range] of Object.entries(deps)) {
    if (range === "workspace:*" && PLUGIN_VERSIONS[name]) {
      deps[name] = PLUGIN_VERSIONS[name];
    }
  }
}

async function transformRootPackageJson(targetDir: string, answers: Answers): Promise<void> {
  const file = join(targetDir, "package.json");
  const pkg = await readJson<Pkg>(file);

  pkg.name = answers.projectName;

  if (pkg.scripts) {
    delete pkg.scripts.release;
    // Source's prepare runs `lefthook install`, which fails without a git repo
    // and crashes downstream `bun install`. Users opt in by running `lefthook install`.
    delete pkg.scripts.prepare;
  }
  if (pkg.devDependencies) {
    for (const dep of Object.keys(pkg.devDependencies)) {
      if (dep.startsWith("@semantic-release/") || dep === "multi-semantic-release") {
        // oxlint-disable-next-line typescript/no-dynamic-delete
        delete pkg.devDependencies[dep];
      }
    }
  }

  await writeJson(file, pkg);
}

async function transformCmsPackageJson(targetDir: string): Promise<void> {
  const file = join(targetDir, "apps/cms/package.json");
  const pkg = await readJson<Pkg>(file);
  rewritePluginRefs(pkg.dependencies);
  rewritePluginRefs(pkg.devDependencies);
  await writeJson(file, pkg);
}

function escapeEnvValue(value: string): string {
  if (value === "") return "";
  return `'${value.replace(/'/gu, "'\\''")}'`;
}

function envLine(key: string, value: string, optional = false): string {
  if (optional && value === "") return `# ${key}=`;
  return `${key}=${escapeEnvValue(value)}`;
}

async function writeEnvFile(targetDir: string, answers: Answers): Promise<void> {
  const lines = [
    "# Generated by create-ideal-cms",
    envLine("DATABASE_URL", answers.databaseUrl),
    envLine("PAYLOAD_SECRET", answers.payloadSecret),
    envLine("NEXT_PUBLIC_SERVER_URL", answers.publicServerUrl),
    "",
    "# Used to validate preview requests",
    envLine("PREVIEW_SECRET", answers.payloadSecret.slice(0, 32)),
    "",
    "# Vercel Blob Storage (for media uploads)",
    envLine("BLOB_READ_WRITE_TOKEN", answers.blobToken, true),
    "",
    "# AI SEO + translator. The translator plugin instantiates OpenAI at config-load,",
    "# so a non-empty value is required for payload to boot. Replace with a real key",
    "# from https://platform.openai.com/api-keys to actually use these features.",
    envLine("OPENAI_API_KEY", answers.openaiApiKey || "sk-placeholder-replace-with-real-key"),
    "",
    "# OIDC SSO (optional)",
    envLine("OIDC_ISSUER", answers.oidcIssuer, true),
    envLine("OIDC_CLIENT_ID", answers.oidcClientId, true),
    envLine("OIDC_CLIENT_SECRET", answers.oidcClientSecret, true),
    "",
  ];
  await writeFile(join(targetDir, "apps/cms/.env"), `${lines.join("\n")}\n`);
}

async function overrideThemeColor(targetDir: string, hex: string): Promise<void> {
  const file = join(targetDir, "packages/tailwind-config/base.css");
  const css = await readFile(file, "utf-8");
  const overlay = `
/* create-ideal-cms: brand color overlay */
@theme {
  --color-primary: ${hex};
}
`;
  await writeFile(file, `${css.trimEnd()}\n${overlay}`);
}

export async function applyTransforms(answers: Answers): Promise<void> {
  await transformRootPackageJson(answers.targetDir, answers);
  await transformCmsPackageJson(answers.targetDir);
  await writeEnvFile(answers.targetDir, answers);
  await overrideThemeColor(answers.targetDir, answers.primaryColor);
}
