import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  // Migrate existing data before changing enums
  await db.execute(sql`
    UPDATE "page_blocks_hero" SET "section_padding_x" = 'base' WHERE "section_padding_x" = 'large';
    UPDATE "page_blocks_text_section" SET "section_padding_x" = 'base' WHERE "section_padding_x" = 'large';
    UPDATE "page_blocks_content" SET "section_padding_x" = 'base' WHERE "section_padding_x" = 'large';
    UPDATE "page_blocks_faq" SET "section_padding_x" = 'base' WHERE "section_padding_x" = 'large';
    UPDATE "page_blocks_testimonials_list" SET "section_padding_x" = 'base' WHERE "section_padding_x" = 'large';
    UPDATE "page_blocks_cards_grid" SET "section_padding_x" = 'base' WHERE "section_padding_x" = 'large';
    UPDATE "page_blocks_carousel" SET "section_padding_x" = 'base' WHERE "section_padding_x" = 'large';
    UPDATE "page_blocks_logos" SET "section_padding_x" = 'base' WHERE "section_padding_x" = 'large';
    UPDATE "page_blocks_links_list" SET "section_padding_x" = 'base' WHERE "section_padding_x" = 'large';
    UPDATE "_page_v_blocks_hero" SET "section_padding_x" = 'base' WHERE "section_padding_x" = 'large';
    UPDATE "_page_v_blocks_text_section" SET "section_padding_x" = 'base' WHERE "section_padding_x" = 'large';
    UPDATE "_page_v_blocks_content" SET "section_padding_x" = 'base' WHERE "section_padding_x" = 'large';
    UPDATE "_page_v_blocks_faq" SET "section_padding_x" = 'base' WHERE "section_padding_x" = 'large';
    UPDATE "_page_v_blocks_testimonials_list" SET "section_padding_x" = 'base' WHERE "section_padding_x" = 'large';
    UPDATE "_page_v_blocks_cards_grid" SET "section_padding_x" = 'base' WHERE "section_padding_x" = 'large';
    UPDATE "_page_v_blocks_carousel" SET "section_padding_x" = 'base' WHERE "section_padding_x" = 'large';
    UPDATE "_page_v_blocks_logos" SET "section_padding_x" = 'base' WHERE "section_padding_x" = 'large';
    UPDATE "_page_v_blocks_links_list" SET "section_padding_x" = 'base' WHERE "section_padding_x" = 'large';

    UPDATE "page_blocks_hero" SET "section_max_width" = 'base' WHERE "section_max_width" = 'small';
    UPDATE "page_blocks_text_section" SET "section_max_width" = 'base' WHERE "section_max_width" = 'small';
    UPDATE "page_blocks_content" SET "section_max_width" = 'base' WHERE "section_max_width" = 'small';
    UPDATE "page_blocks_faq" SET "section_max_width" = 'base' WHERE "section_max_width" = 'small';
    UPDATE "page_blocks_testimonials_list" SET "section_max_width" = 'base' WHERE "section_max_width" = 'small';
    UPDATE "page_blocks_cards_grid" SET "section_max_width" = 'base' WHERE "section_max_width" = 'small';
    UPDATE "page_blocks_carousel" SET "section_max_width" = 'base' WHERE "section_max_width" = 'small';
    UPDATE "page_blocks_logos" SET "section_max_width" = 'base' WHERE "section_max_width" = 'small';
    UPDATE "page_blocks_links_list" SET "section_max_width" = 'base' WHERE "section_max_width" = 'small';
    UPDATE "_page_v_blocks_hero" SET "section_max_width" = 'base' WHERE "section_max_width" = 'small';
    UPDATE "_page_v_blocks_text_section" SET "section_max_width" = 'base' WHERE "section_max_width" = 'small';
    UPDATE "_page_v_blocks_content" SET "section_max_width" = 'base' WHERE "section_max_width" = 'small';
    UPDATE "_page_v_blocks_faq" SET "section_max_width" = 'base' WHERE "section_max_width" = 'small';
    UPDATE "_page_v_blocks_testimonials_list" SET "section_max_width" = 'base' WHERE "section_max_width" = 'small';
    UPDATE "_page_v_blocks_cards_grid" SET "section_max_width" = 'base' WHERE "section_max_width" = 'small';
    UPDATE "_page_v_blocks_carousel" SET "section_max_width" = 'base' WHERE "section_max_width" = 'small';
    UPDATE "_page_v_blocks_logos" SET "section_max_width" = 'base' WHERE "section_max_width" = 'small';
    UPDATE "_page_v_blocks_links_list" SET "section_max_width" = 'base' WHERE "section_max_width" = 'small';
  `);

  await db.execute(sql`
   CREATE TYPE "public"."sec_bg_ovrly" AS ENUM('black', 'white');
  ALTER TABLE "page_blocks_hero" DROP CONSTRAINT "page_blocks_hero_section_background_image_id_media_id_fk";
  
  ALTER TABLE "page_blocks_text_section" DROP CONSTRAINT "page_blocks_text_section_section_background_image_id_media_id_fk";
  
  ALTER TABLE "page_blocks_content" DROP CONSTRAINT "page_blocks_content_section_background_image_id_media_id_fk";
  
  ALTER TABLE "page_blocks_faq" DROP CONSTRAINT "page_blocks_faq_section_background_image_id_media_id_fk";
  
  ALTER TABLE "page_blocks_testimonials_list" DROP CONSTRAINT "page_blocks_testimonials_list_section_background_image_id_media_id_fk";
  
  ALTER TABLE "page_blocks_cards_grid" DROP CONSTRAINT "page_blocks_cards_grid_section_background_image_id_media_id_fk";
  
  ALTER TABLE "page_blocks_carousel" DROP CONSTRAINT "page_blocks_carousel_section_background_image_id_media_id_fk";
  
  ALTER TABLE "page_blocks_logos" DROP CONSTRAINT "page_blocks_logos_section_background_image_id_media_id_fk";
  
  ALTER TABLE "page_blocks_links_list" DROP CONSTRAINT "page_blocks_links_list_section_background_image_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_hero" DROP CONSTRAINT "_page_v_blocks_hero_section_background_image_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_text_section" DROP CONSTRAINT "_page_v_blocks_text_section_section_background_image_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_content" DROP CONSTRAINT "_page_v_blocks_content_section_background_image_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_faq" DROP CONSTRAINT "_page_v_blocks_faq_section_background_image_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_testimonials_list" DROP CONSTRAINT "_page_v_blocks_testimonials_list_section_background_image_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_cards_grid" DROP CONSTRAINT "_page_v_blocks_cards_grid_section_background_image_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_carousel" DROP CONSTRAINT "_page_v_blocks_carousel_section_background_image_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_logos" DROP CONSTRAINT "_page_v_blocks_logos_section_background_image_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_links_list" DROP CONSTRAINT "_page_v_blocks_links_list_section_background_image_id_media_id_fk";
  
  ALTER TABLE "page_blocks_hero" ALTER COLUMN "section_padding_x" SET DATA TYPE text;
  ALTER TABLE "page_blocks_hero" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_hero_section_padding_x";
  CREATE TYPE "public"."enum_page_blocks_hero_section_padding_x" AS ENUM('none', 'base');
  ALTER TABLE "page_blocks_hero" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::"public"."enum_page_blocks_hero_section_padding_x";
  ALTER TABLE "page_blocks_hero" ALTER COLUMN "section_padding_x" SET DATA TYPE "public"."enum_page_blocks_hero_section_padding_x" USING "section_padding_x"::"public"."enum_page_blocks_hero_section_padding_x";
  ALTER TABLE "page_blocks_hero" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "page_blocks_hero" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_hero_section_max_width";
  CREATE TYPE "public"."enum_page_blocks_hero_section_max_width" AS ENUM('none', 'base', 'full');
  ALTER TABLE "page_blocks_hero" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum_page_blocks_hero_section_max_width";
  ALTER TABLE "page_blocks_hero" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum_page_blocks_hero_section_max_width" USING "section_max_width"::"public"."enum_page_blocks_hero_section_max_width";
  ALTER TABLE "page_blocks_text_section" ALTER COLUMN "section_padding_x" SET DATA TYPE text;
  ALTER TABLE "page_blocks_text_section" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_text_section_section_padding_x";
  CREATE TYPE "public"."enum_page_blocks_text_section_section_padding_x" AS ENUM('none', 'base');
  ALTER TABLE "page_blocks_text_section" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::"public"."enum_page_blocks_text_section_section_padding_x";
  ALTER TABLE "page_blocks_text_section" ALTER COLUMN "section_padding_x" SET DATA TYPE "public"."enum_page_blocks_text_section_section_padding_x" USING "section_padding_x"::"public"."enum_page_blocks_text_section_section_padding_x";
  ALTER TABLE "page_blocks_text_section" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "page_blocks_text_section" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_text_section_section_max_width";
  CREATE TYPE "public"."enum_page_blocks_text_section_section_max_width" AS ENUM('none', 'base', 'full');
  ALTER TABLE "page_blocks_text_section" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum_page_blocks_text_section_section_max_width";
  ALTER TABLE "page_blocks_text_section" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum_page_blocks_text_section_section_max_width" USING "section_max_width"::"public"."enum_page_blocks_text_section_section_max_width";
  ALTER TABLE "page_blocks_content" ALTER COLUMN "section_padding_x" SET DATA TYPE text;
  ALTER TABLE "page_blocks_content" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_content_section_padding_x";
  CREATE TYPE "public"."enum_page_blocks_content_section_padding_x" AS ENUM('none', 'base');
  ALTER TABLE "page_blocks_content" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::"public"."enum_page_blocks_content_section_padding_x";
  ALTER TABLE "page_blocks_content" ALTER COLUMN "section_padding_x" SET DATA TYPE "public"."enum_page_blocks_content_section_padding_x" USING "section_padding_x"::"public"."enum_page_blocks_content_section_padding_x";
  ALTER TABLE "page_blocks_content" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "page_blocks_content" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_content_section_max_width";
  CREATE TYPE "public"."enum_page_blocks_content_section_max_width" AS ENUM('none', 'base', 'full');
  ALTER TABLE "page_blocks_content" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum_page_blocks_content_section_max_width";
  ALTER TABLE "page_blocks_content" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum_page_blocks_content_section_max_width" USING "section_max_width"::"public"."enum_page_blocks_content_section_max_width";
  ALTER TABLE "page_blocks_faq" ALTER COLUMN "section_padding_x" SET DATA TYPE text;
  ALTER TABLE "page_blocks_faq" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_faq_section_padding_x";
  CREATE TYPE "public"."enum_page_blocks_faq_section_padding_x" AS ENUM('none', 'base');
  ALTER TABLE "page_blocks_faq" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::"public"."enum_page_blocks_faq_section_padding_x";
  ALTER TABLE "page_blocks_faq" ALTER COLUMN "section_padding_x" SET DATA TYPE "public"."enum_page_blocks_faq_section_padding_x" USING "section_padding_x"::"public"."enum_page_blocks_faq_section_padding_x";
  ALTER TABLE "page_blocks_faq" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "page_blocks_faq" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_faq_section_max_width";
  CREATE TYPE "public"."enum_page_blocks_faq_section_max_width" AS ENUM('none', 'base', 'full');
  ALTER TABLE "page_blocks_faq" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum_page_blocks_faq_section_max_width";
  ALTER TABLE "page_blocks_faq" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum_page_blocks_faq_section_max_width" USING "section_max_width"::"public"."enum_page_blocks_faq_section_max_width";
  ALTER TABLE "page_blocks_testimonials_list" ALTER COLUMN "section_padding_x" SET DATA TYPE text;
  ALTER TABLE "page_blocks_testimonials_list" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_testimonials_list_section_padding_x";
  CREATE TYPE "public"."enum_page_blocks_testimonials_list_section_padding_x" AS ENUM('none', 'base');
  ALTER TABLE "page_blocks_testimonials_list" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::"public"."enum_page_blocks_testimonials_list_section_padding_x";
  ALTER TABLE "page_blocks_testimonials_list" ALTER COLUMN "section_padding_x" SET DATA TYPE "public"."enum_page_blocks_testimonials_list_section_padding_x" USING "section_padding_x"::"public"."enum_page_blocks_testimonials_list_section_padding_x";
  ALTER TABLE "page_blocks_testimonials_list" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "page_blocks_testimonials_list" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_testimonials_list_section_max_width";
  CREATE TYPE "public"."enum_page_blocks_testimonials_list_section_max_width" AS ENUM('none', 'base', 'full');
  ALTER TABLE "page_blocks_testimonials_list" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum_page_blocks_testimonials_list_section_max_width";
  ALTER TABLE "page_blocks_testimonials_list" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum_page_blocks_testimonials_list_section_max_width" USING "section_max_width"::"public"."enum_page_blocks_testimonials_list_section_max_width";
  ALTER TABLE "page_blocks_cards_grid" ALTER COLUMN "section_padding_x" SET DATA TYPE text;
  ALTER TABLE "page_blocks_cards_grid" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_cards_grid_section_padding_x";
  CREATE TYPE "public"."enum_page_blocks_cards_grid_section_padding_x" AS ENUM('none', 'base');
  ALTER TABLE "page_blocks_cards_grid" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::"public"."enum_page_blocks_cards_grid_section_padding_x";
  ALTER TABLE "page_blocks_cards_grid" ALTER COLUMN "section_padding_x" SET DATA TYPE "public"."enum_page_blocks_cards_grid_section_padding_x" USING "section_padding_x"::"public"."enum_page_blocks_cards_grid_section_padding_x";
  ALTER TABLE "page_blocks_cards_grid" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "page_blocks_cards_grid" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_cards_grid_section_max_width";
  CREATE TYPE "public"."enum_page_blocks_cards_grid_section_max_width" AS ENUM('none', 'base', 'full');
  ALTER TABLE "page_blocks_cards_grid" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum_page_blocks_cards_grid_section_max_width";
  ALTER TABLE "page_blocks_cards_grid" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum_page_blocks_cards_grid_section_max_width" USING "section_max_width"::"public"."enum_page_blocks_cards_grid_section_max_width";
  ALTER TABLE "page_blocks_carousel" ALTER COLUMN "section_padding_x" SET DATA TYPE text;
  ALTER TABLE "page_blocks_carousel" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_carousel_section_padding_x";
  CREATE TYPE "public"."enum_page_blocks_carousel_section_padding_x" AS ENUM('none', 'base');
  ALTER TABLE "page_blocks_carousel" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::"public"."enum_page_blocks_carousel_section_padding_x";
  ALTER TABLE "page_blocks_carousel" ALTER COLUMN "section_padding_x" SET DATA TYPE "public"."enum_page_blocks_carousel_section_padding_x" USING "section_padding_x"::"public"."enum_page_blocks_carousel_section_padding_x";
  ALTER TABLE "page_blocks_carousel" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "page_blocks_carousel" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_carousel_section_max_width";
  CREATE TYPE "public"."enum_page_blocks_carousel_section_max_width" AS ENUM('none', 'base', 'full');
  ALTER TABLE "page_blocks_carousel" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum_page_blocks_carousel_section_max_width";
  ALTER TABLE "page_blocks_carousel" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum_page_blocks_carousel_section_max_width" USING "section_max_width"::"public"."enum_page_blocks_carousel_section_max_width";
  ALTER TABLE "page_blocks_logos" ALTER COLUMN "section_padding_x" SET DATA TYPE text;
  ALTER TABLE "page_blocks_logos" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_logos_section_padding_x";
  CREATE TYPE "public"."enum_page_blocks_logos_section_padding_x" AS ENUM('none', 'base');
  ALTER TABLE "page_blocks_logos" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::"public"."enum_page_blocks_logos_section_padding_x";
  ALTER TABLE "page_blocks_logos" ALTER COLUMN "section_padding_x" SET DATA TYPE "public"."enum_page_blocks_logos_section_padding_x" USING "section_padding_x"::"public"."enum_page_blocks_logos_section_padding_x";
  ALTER TABLE "page_blocks_logos" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "page_blocks_logos" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_logos_section_max_width";
  CREATE TYPE "public"."enum_page_blocks_logos_section_max_width" AS ENUM('none', 'base', 'full');
  ALTER TABLE "page_blocks_logos" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum_page_blocks_logos_section_max_width";
  ALTER TABLE "page_blocks_logos" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum_page_blocks_logos_section_max_width" USING "section_max_width"::"public"."enum_page_blocks_logos_section_max_width";
  ALTER TABLE "page_blocks_links_list" ALTER COLUMN "section_padding_x" SET DATA TYPE text;
  ALTER TABLE "page_blocks_links_list" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_links_list_section_padding_x";
  CREATE TYPE "public"."enum_page_blocks_links_list_section_padding_x" AS ENUM('none', 'base');
  ALTER TABLE "page_blocks_links_list" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::"public"."enum_page_blocks_links_list_section_padding_x";
  ALTER TABLE "page_blocks_links_list" ALTER COLUMN "section_padding_x" SET DATA TYPE "public"."enum_page_blocks_links_list_section_padding_x" USING "section_padding_x"::"public"."enum_page_blocks_links_list_section_padding_x";
  ALTER TABLE "page_blocks_links_list" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "page_blocks_links_list" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_links_list_section_max_width";
  CREATE TYPE "public"."enum_page_blocks_links_list_section_max_width" AS ENUM('none', 'base', 'full');
  ALTER TABLE "page_blocks_links_list" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum_page_blocks_links_list_section_max_width";
  ALTER TABLE "page_blocks_links_list" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum_page_blocks_links_list_section_max_width" USING "section_max_width"::"public"."enum_page_blocks_links_list_section_max_width";
  ALTER TABLE "_page_v_blocks_hero" ALTER COLUMN "section_padding_x" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_hero" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_hero_section_padding_x";
  CREATE TYPE "public"."enum__page_v_blocks_hero_section_padding_x" AS ENUM('none', 'base');
  ALTER TABLE "_page_v_blocks_hero" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::"public"."enum__page_v_blocks_hero_section_padding_x";
  ALTER TABLE "_page_v_blocks_hero" ALTER COLUMN "section_padding_x" SET DATA TYPE "public"."enum__page_v_blocks_hero_section_padding_x" USING "section_padding_x"::"public"."enum__page_v_blocks_hero_section_padding_x";
  ALTER TABLE "_page_v_blocks_hero" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_hero" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_hero_section_max_width";
  CREATE TYPE "public"."enum__page_v_blocks_hero_section_max_width" AS ENUM('none', 'base', 'full');
  ALTER TABLE "_page_v_blocks_hero" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum__page_v_blocks_hero_section_max_width";
  ALTER TABLE "_page_v_blocks_hero" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum__page_v_blocks_hero_section_max_width" USING "section_max_width"::"public"."enum__page_v_blocks_hero_section_max_width";
  ALTER TABLE "_page_v_blocks_text_section" ALTER COLUMN "section_padding_x" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_text_section" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_text_section_section_padding_x";
  CREATE TYPE "public"."enum__page_v_blocks_text_section_section_padding_x" AS ENUM('none', 'base');
  ALTER TABLE "_page_v_blocks_text_section" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::"public"."enum__page_v_blocks_text_section_section_padding_x";
  ALTER TABLE "_page_v_blocks_text_section" ALTER COLUMN "section_padding_x" SET DATA TYPE "public"."enum__page_v_blocks_text_section_section_padding_x" USING "section_padding_x"::"public"."enum__page_v_blocks_text_section_section_padding_x";
  ALTER TABLE "_page_v_blocks_text_section" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_text_section" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_text_section_section_max_width";
  CREATE TYPE "public"."enum__page_v_blocks_text_section_section_max_width" AS ENUM('none', 'base', 'full');
  ALTER TABLE "_page_v_blocks_text_section" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum__page_v_blocks_text_section_section_max_width";
  ALTER TABLE "_page_v_blocks_text_section" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum__page_v_blocks_text_section_section_max_width" USING "section_max_width"::"public"."enum__page_v_blocks_text_section_section_max_width";
  ALTER TABLE "_page_v_blocks_content" ALTER COLUMN "section_padding_x" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_content" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_content_section_padding_x";
  CREATE TYPE "public"."enum__page_v_blocks_content_section_padding_x" AS ENUM('none', 'base');
  ALTER TABLE "_page_v_blocks_content" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::"public"."enum__page_v_blocks_content_section_padding_x";
  ALTER TABLE "_page_v_blocks_content" ALTER COLUMN "section_padding_x" SET DATA TYPE "public"."enum__page_v_blocks_content_section_padding_x" USING "section_padding_x"::"public"."enum__page_v_blocks_content_section_padding_x";
  ALTER TABLE "_page_v_blocks_content" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_content" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_content_section_max_width";
  CREATE TYPE "public"."enum__page_v_blocks_content_section_max_width" AS ENUM('none', 'base', 'full');
  ALTER TABLE "_page_v_blocks_content" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum__page_v_blocks_content_section_max_width";
  ALTER TABLE "_page_v_blocks_content" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum__page_v_blocks_content_section_max_width" USING "section_max_width"::"public"."enum__page_v_blocks_content_section_max_width";
  ALTER TABLE "_page_v_blocks_faq" ALTER COLUMN "section_padding_x" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_faq" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_faq_section_padding_x";
  CREATE TYPE "public"."enum__page_v_blocks_faq_section_padding_x" AS ENUM('none', 'base');
  ALTER TABLE "_page_v_blocks_faq" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::"public"."enum__page_v_blocks_faq_section_padding_x";
  ALTER TABLE "_page_v_blocks_faq" ALTER COLUMN "section_padding_x" SET DATA TYPE "public"."enum__page_v_blocks_faq_section_padding_x" USING "section_padding_x"::"public"."enum__page_v_blocks_faq_section_padding_x";
  ALTER TABLE "_page_v_blocks_faq" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_faq" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_faq_section_max_width";
  CREATE TYPE "public"."enum__page_v_blocks_faq_section_max_width" AS ENUM('none', 'base', 'full');
  ALTER TABLE "_page_v_blocks_faq" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum__page_v_blocks_faq_section_max_width";
  ALTER TABLE "_page_v_blocks_faq" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum__page_v_blocks_faq_section_max_width" USING "section_max_width"::"public"."enum__page_v_blocks_faq_section_max_width";
  ALTER TABLE "_page_v_blocks_testimonials_list" ALTER COLUMN "section_padding_x" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_testimonials_list" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_testimonials_list_section_padding_x";
  CREATE TYPE "public"."enum__page_v_blocks_testimonials_list_section_padding_x" AS ENUM('none', 'base');
  ALTER TABLE "_page_v_blocks_testimonials_list" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::"public"."enum__page_v_blocks_testimonials_list_section_padding_x";
  ALTER TABLE "_page_v_blocks_testimonials_list" ALTER COLUMN "section_padding_x" SET DATA TYPE "public"."enum__page_v_blocks_testimonials_list_section_padding_x" USING "section_padding_x"::"public"."enum__page_v_blocks_testimonials_list_section_padding_x";
  ALTER TABLE "_page_v_blocks_testimonials_list" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_testimonials_list" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_testimonials_list_section_max_width";
  CREATE TYPE "public"."enum__page_v_blocks_testimonials_list_section_max_width" AS ENUM('none', 'base', 'full');
  ALTER TABLE "_page_v_blocks_testimonials_list" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum__page_v_blocks_testimonials_list_section_max_width";
  ALTER TABLE "_page_v_blocks_testimonials_list" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum__page_v_blocks_testimonials_list_section_max_width" USING "section_max_width"::"public"."enum__page_v_blocks_testimonials_list_section_max_width";
  ALTER TABLE "_page_v_blocks_cards_grid" ALTER COLUMN "section_padding_x" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_cards_grid" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_cards_grid_section_padding_x";
  CREATE TYPE "public"."enum__page_v_blocks_cards_grid_section_padding_x" AS ENUM('none', 'base');
  ALTER TABLE "_page_v_blocks_cards_grid" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::"public"."enum__page_v_blocks_cards_grid_section_padding_x";
  ALTER TABLE "_page_v_blocks_cards_grid" ALTER COLUMN "section_padding_x" SET DATA TYPE "public"."enum__page_v_blocks_cards_grid_section_padding_x" USING "section_padding_x"::"public"."enum__page_v_blocks_cards_grid_section_padding_x";
  ALTER TABLE "_page_v_blocks_cards_grid" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_cards_grid" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_cards_grid_section_max_width";
  CREATE TYPE "public"."enum__page_v_blocks_cards_grid_section_max_width" AS ENUM('none', 'base', 'full');
  ALTER TABLE "_page_v_blocks_cards_grid" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum__page_v_blocks_cards_grid_section_max_width";
  ALTER TABLE "_page_v_blocks_cards_grid" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum__page_v_blocks_cards_grid_section_max_width" USING "section_max_width"::"public"."enum__page_v_blocks_cards_grid_section_max_width";
  ALTER TABLE "_page_v_blocks_carousel" ALTER COLUMN "section_padding_x" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_carousel" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_carousel_section_padding_x";
  CREATE TYPE "public"."enum__page_v_blocks_carousel_section_padding_x" AS ENUM('none', 'base');
  ALTER TABLE "_page_v_blocks_carousel" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::"public"."enum__page_v_blocks_carousel_section_padding_x";
  ALTER TABLE "_page_v_blocks_carousel" ALTER COLUMN "section_padding_x" SET DATA TYPE "public"."enum__page_v_blocks_carousel_section_padding_x" USING "section_padding_x"::"public"."enum__page_v_blocks_carousel_section_padding_x";
  ALTER TABLE "_page_v_blocks_carousel" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_carousel" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_carousel_section_max_width";
  CREATE TYPE "public"."enum__page_v_blocks_carousel_section_max_width" AS ENUM('none', 'base', 'full');
  ALTER TABLE "_page_v_blocks_carousel" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum__page_v_blocks_carousel_section_max_width";
  ALTER TABLE "_page_v_blocks_carousel" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum__page_v_blocks_carousel_section_max_width" USING "section_max_width"::"public"."enum__page_v_blocks_carousel_section_max_width";
  ALTER TABLE "_page_v_blocks_logos" ALTER COLUMN "section_padding_x" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_logos" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_logos_section_padding_x";
  CREATE TYPE "public"."enum__page_v_blocks_logos_section_padding_x" AS ENUM('none', 'base');
  ALTER TABLE "_page_v_blocks_logos" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::"public"."enum__page_v_blocks_logos_section_padding_x";
  ALTER TABLE "_page_v_blocks_logos" ALTER COLUMN "section_padding_x" SET DATA TYPE "public"."enum__page_v_blocks_logos_section_padding_x" USING "section_padding_x"::"public"."enum__page_v_blocks_logos_section_padding_x";
  ALTER TABLE "_page_v_blocks_logos" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_logos" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_logos_section_max_width";
  CREATE TYPE "public"."enum__page_v_blocks_logos_section_max_width" AS ENUM('none', 'base', 'full');
  ALTER TABLE "_page_v_blocks_logos" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum__page_v_blocks_logos_section_max_width";
  ALTER TABLE "_page_v_blocks_logos" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum__page_v_blocks_logos_section_max_width" USING "section_max_width"::"public"."enum__page_v_blocks_logos_section_max_width";
  ALTER TABLE "_page_v_blocks_links_list" ALTER COLUMN "section_padding_x" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_links_list" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_links_list_section_padding_x";
  CREATE TYPE "public"."enum__page_v_blocks_links_list_section_padding_x" AS ENUM('none', 'base');
  ALTER TABLE "_page_v_blocks_links_list" ALTER COLUMN "section_padding_x" SET DEFAULT 'base'::"public"."enum__page_v_blocks_links_list_section_padding_x";
  ALTER TABLE "_page_v_blocks_links_list" ALTER COLUMN "section_padding_x" SET DATA TYPE "public"."enum__page_v_blocks_links_list_section_padding_x" USING "section_padding_x"::"public"."enum__page_v_blocks_links_list_section_padding_x";
  ALTER TABLE "_page_v_blocks_links_list" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_links_list" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_links_list_section_max_width";
  CREATE TYPE "public"."enum__page_v_blocks_links_list_section_max_width" AS ENUM('none', 'base', 'full');
  ALTER TABLE "_page_v_blocks_links_list" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum__page_v_blocks_links_list_section_max_width";
  ALTER TABLE "_page_v_blocks_links_list" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum__page_v_blocks_links_list_section_max_width" USING "section_max_width"::"public"."enum__page_v_blocks_links_list_section_max_width";
  DROP INDEX "page_blocks_hero_section_section_background_image_idx";
  DROP INDEX "page_blocks_text_section_section_section_background_imag_idx";
  DROP INDEX "page_blocks_content_section_section_background_image_idx";
  DROP INDEX "page_blocks_faq_section_section_background_image_idx";
  DROP INDEX "page_blocks_testimonials_list_section_section_background_idx";
  DROP INDEX "page_blocks_cards_grid_section_section_background_image_idx";
  DROP INDEX "page_blocks_carousel_section_section_background_image_idx";
  DROP INDEX "page_blocks_logos_section_section_background_image_idx";
  DROP INDEX "page_blocks_links_list_section_section_background_image_idx";
  DROP INDEX "_page_v_blocks_hero_section_section_background_image_idx";
  DROP INDEX "_page_v_blocks_text_section_section_section_background_i_idx";
  DROP INDEX "_page_v_blocks_content_section_section_background_image_idx";
  DROP INDEX "_page_v_blocks_faq_section_section_background_image_idx";
  DROP INDEX "_page_v_blocks_testimonials_list_section_section_backgro_idx";
  DROP INDEX "_page_v_blocks_cards_grid_section_section_background_ima_idx";
  DROP INDEX "_page_v_blocks_carousel_section_section_background_image_idx";
  DROP INDEX "_page_v_blocks_logos_section_section_background_image_idx";
  DROP INDEX "_page_v_blocks_links_list_section_section_background_ima_idx";
  ALTER TABLE "page_blocks_hero" ADD COLUMN "section_background_media_id" integer;
  ALTER TABLE "page_blocks_hero" ADD COLUMN "section_background_overlay" "sec_bg_ovrly";
  ALTER TABLE "page_blocks_hero" ADD COLUMN "section_background_opacity" numeric DEFAULT 35;
  ALTER TABLE "page_blocks_text_section" ADD COLUMN "section_background_media_id" integer;
  ALTER TABLE "page_blocks_text_section" ADD COLUMN "section_background_overlay" "sec_bg_ovrly";
  ALTER TABLE "page_blocks_text_section" ADD COLUMN "section_background_opacity" numeric DEFAULT 35;
  ALTER TABLE "page_blocks_content" ADD COLUMN "section_background_media_id" integer;
  ALTER TABLE "page_blocks_content" ADD COLUMN "section_background_overlay" "sec_bg_ovrly";
  ALTER TABLE "page_blocks_content" ADD COLUMN "section_background_opacity" numeric DEFAULT 35;
  ALTER TABLE "page_blocks_faq" ADD COLUMN "section_background_media_id" integer;
  ALTER TABLE "page_blocks_faq" ADD COLUMN "section_background_overlay" "sec_bg_ovrly";
  ALTER TABLE "page_blocks_faq" ADD COLUMN "section_background_opacity" numeric DEFAULT 35;
  ALTER TABLE "page_blocks_testimonials_list" ADD COLUMN "section_background_media_id" integer;
  ALTER TABLE "page_blocks_testimonials_list" ADD COLUMN "section_background_overlay" "sec_bg_ovrly";
  ALTER TABLE "page_blocks_testimonials_list" ADD COLUMN "section_background_opacity" numeric DEFAULT 35;
  ALTER TABLE "page_blocks_cards_grid" ADD COLUMN "section_background_media_id" integer;
  ALTER TABLE "page_blocks_cards_grid" ADD COLUMN "section_background_overlay" "sec_bg_ovrly";
  ALTER TABLE "page_blocks_cards_grid" ADD COLUMN "section_background_opacity" numeric DEFAULT 35;
  ALTER TABLE "page_blocks_carousel" ADD COLUMN "section_background_media_id" integer;
  ALTER TABLE "page_blocks_carousel" ADD COLUMN "section_background_overlay" "sec_bg_ovrly";
  ALTER TABLE "page_blocks_carousel" ADD COLUMN "section_background_opacity" numeric DEFAULT 35;
  ALTER TABLE "page_blocks_logos" ADD COLUMN "section_background_media_id" integer;
  ALTER TABLE "page_blocks_logos" ADD COLUMN "section_background_overlay" "sec_bg_ovrly";
  ALTER TABLE "page_blocks_logos" ADD COLUMN "section_background_opacity" numeric DEFAULT 35;
  ALTER TABLE "page_blocks_links_list" ADD COLUMN "section_background_media_id" integer;
  ALTER TABLE "page_blocks_links_list" ADD COLUMN "section_background_overlay" "sec_bg_ovrly";
  ALTER TABLE "page_blocks_links_list" ADD COLUMN "section_background_opacity" numeric DEFAULT 35;
  ALTER TABLE "_page_v_blocks_hero" ADD COLUMN "section_background_media_id" integer;
  ALTER TABLE "_page_v_blocks_hero" ADD COLUMN "section_background_overlay" "sec_bg_ovrly";
  ALTER TABLE "_page_v_blocks_hero" ADD COLUMN "section_background_opacity" numeric DEFAULT 35;
  ALTER TABLE "_page_v_blocks_text_section" ADD COLUMN "section_background_media_id" integer;
  ALTER TABLE "_page_v_blocks_text_section" ADD COLUMN "section_background_overlay" "sec_bg_ovrly";
  ALTER TABLE "_page_v_blocks_text_section" ADD COLUMN "section_background_opacity" numeric DEFAULT 35;
  ALTER TABLE "_page_v_blocks_content" ADD COLUMN "section_background_media_id" integer;
  ALTER TABLE "_page_v_blocks_content" ADD COLUMN "section_background_overlay" "sec_bg_ovrly";
  ALTER TABLE "_page_v_blocks_content" ADD COLUMN "section_background_opacity" numeric DEFAULT 35;
  ALTER TABLE "_page_v_blocks_faq" ADD COLUMN "section_background_media_id" integer;
  ALTER TABLE "_page_v_blocks_faq" ADD COLUMN "section_background_overlay" "sec_bg_ovrly";
  ALTER TABLE "_page_v_blocks_faq" ADD COLUMN "section_background_opacity" numeric DEFAULT 35;
  ALTER TABLE "_page_v_blocks_testimonials_list" ADD COLUMN "section_background_media_id" integer;
  ALTER TABLE "_page_v_blocks_testimonials_list" ADD COLUMN "section_background_overlay" "sec_bg_ovrly";
  ALTER TABLE "_page_v_blocks_testimonials_list" ADD COLUMN "section_background_opacity" numeric DEFAULT 35;
  ALTER TABLE "_page_v_blocks_cards_grid" ADD COLUMN "section_background_media_id" integer;
  ALTER TABLE "_page_v_blocks_cards_grid" ADD COLUMN "section_background_overlay" "sec_bg_ovrly";
  ALTER TABLE "_page_v_blocks_cards_grid" ADD COLUMN "section_background_opacity" numeric DEFAULT 35;
  ALTER TABLE "_page_v_blocks_carousel" ADD COLUMN "section_background_media_id" integer;
  ALTER TABLE "_page_v_blocks_carousel" ADD COLUMN "section_background_overlay" "sec_bg_ovrly";
  ALTER TABLE "_page_v_blocks_carousel" ADD COLUMN "section_background_opacity" numeric DEFAULT 35;
  ALTER TABLE "_page_v_blocks_logos" ADD COLUMN "section_background_media_id" integer;
  ALTER TABLE "_page_v_blocks_logos" ADD COLUMN "section_background_overlay" "sec_bg_ovrly";
  ALTER TABLE "_page_v_blocks_logos" ADD COLUMN "section_background_opacity" numeric DEFAULT 35;
  ALTER TABLE "_page_v_blocks_links_list" ADD COLUMN "section_background_media_id" integer;
  ALTER TABLE "_page_v_blocks_links_list" ADD COLUMN "section_background_overlay" "sec_bg_ovrly";
  ALTER TABLE "_page_v_blocks_links_list" ADD COLUMN "section_background_opacity" numeric DEFAULT 35;
  ALTER TABLE "page_blocks_hero" ADD CONSTRAINT "page_blocks_hero_section_background_media_id_media_id_fk" FOREIGN KEY ("section_background_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_text_section" ADD CONSTRAINT "page_blocks_text_section_section_background_media_id_media_id_fk" FOREIGN KEY ("section_background_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_content" ADD CONSTRAINT "page_blocks_content_section_background_media_id_media_id_fk" FOREIGN KEY ("section_background_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_faq" ADD CONSTRAINT "page_blocks_faq_section_background_media_id_media_id_fk" FOREIGN KEY ("section_background_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_testimonials_list" ADD CONSTRAINT "page_blocks_testimonials_list_section_background_media_id_media_id_fk" FOREIGN KEY ("section_background_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_cards_grid" ADD CONSTRAINT "page_blocks_cards_grid_section_background_media_id_media_id_fk" FOREIGN KEY ("section_background_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_carousel" ADD CONSTRAINT "page_blocks_carousel_section_background_media_id_media_id_fk" FOREIGN KEY ("section_background_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_logos" ADD CONSTRAINT "page_blocks_logos_section_background_media_id_media_id_fk" FOREIGN KEY ("section_background_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_links_list" ADD CONSTRAINT "page_blocks_links_list_section_background_media_id_media_id_fk" FOREIGN KEY ("section_background_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_hero" ADD CONSTRAINT "_page_v_blocks_hero_section_background_media_id_media_id_fk" FOREIGN KEY ("section_background_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_text_section" ADD CONSTRAINT "_page_v_blocks_text_section_section_background_media_id_media_id_fk" FOREIGN KEY ("section_background_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_content" ADD CONSTRAINT "_page_v_blocks_content_section_background_media_id_media_id_fk" FOREIGN KEY ("section_background_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_faq" ADD CONSTRAINT "_page_v_blocks_faq_section_background_media_id_media_id_fk" FOREIGN KEY ("section_background_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_testimonials_list" ADD CONSTRAINT "_page_v_blocks_testimonials_list_section_background_media_id_media_id_fk" FOREIGN KEY ("section_background_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_cards_grid" ADD CONSTRAINT "_page_v_blocks_cards_grid_section_background_media_id_media_id_fk" FOREIGN KEY ("section_background_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_carousel" ADD CONSTRAINT "_page_v_blocks_carousel_section_background_media_id_media_id_fk" FOREIGN KEY ("section_background_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_logos" ADD CONSTRAINT "_page_v_blocks_logos_section_background_media_id_media_id_fk" FOREIGN KEY ("section_background_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_links_list" ADD CONSTRAINT "_page_v_blocks_links_list_section_background_media_id_media_id_fk" FOREIGN KEY ("section_background_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "page_blocks_hero_section_background_section_background_m_idx" ON "page_blocks_hero" USING btree ("section_background_media_id");
  CREATE INDEX "page_blocks_text_section_section_background_section_back_idx" ON "page_blocks_text_section" USING btree ("section_background_media_id");
  CREATE INDEX "page_blocks_content_section_background_section_backgroun_idx" ON "page_blocks_content" USING btree ("section_background_media_id");
  CREATE INDEX "page_blocks_faq_section_background_section_background_me_idx" ON "page_blocks_faq" USING btree ("section_background_media_id");
  CREATE INDEX "page_blocks_testimonials_list_section_background_section_idx" ON "page_blocks_testimonials_list" USING btree ("section_background_media_id");
  CREATE INDEX "page_blocks_cards_grid_section_background_section_backgr_idx" ON "page_blocks_cards_grid" USING btree ("section_background_media_id");
  CREATE INDEX "page_blocks_carousel_section_background_section_backgrou_idx" ON "page_blocks_carousel" USING btree ("section_background_media_id");
  CREATE INDEX "page_blocks_logos_section_background_section_background__idx" ON "page_blocks_logos" USING btree ("section_background_media_id");
  CREATE INDEX "page_blocks_links_list_section_background_section_backgr_idx" ON "page_blocks_links_list" USING btree ("section_background_media_id");
  CREATE INDEX "_page_v_blocks_hero_section_background_section_backgroun_idx" ON "_page_v_blocks_hero" USING btree ("section_background_media_id");
  CREATE INDEX "_page_v_blocks_text_section_section_background_section_b_idx" ON "_page_v_blocks_text_section" USING btree ("section_background_media_id");
  CREATE INDEX "_page_v_blocks_content_section_background_section_backgr_idx" ON "_page_v_blocks_content" USING btree ("section_background_media_id");
  CREATE INDEX "_page_v_blocks_faq_section_background_section_background_idx" ON "_page_v_blocks_faq" USING btree ("section_background_media_id");
  CREATE INDEX "_page_v_blocks_testimonials_list_section_background_sect_idx" ON "_page_v_blocks_testimonials_list" USING btree ("section_background_media_id");
  CREATE INDEX "_page_v_blocks_cards_grid_section_background_section_bac_idx" ON "_page_v_blocks_cards_grid" USING btree ("section_background_media_id");
  CREATE INDEX "_page_v_blocks_carousel_section_background_section_backg_idx" ON "_page_v_blocks_carousel" USING btree ("section_background_media_id");
  CREATE INDEX "_page_v_blocks_logos_section_background_section_backgrou_idx" ON "_page_v_blocks_logos" USING btree ("section_background_media_id");
  CREATE INDEX "_page_v_blocks_links_list_section_background_section_bac_idx" ON "_page_v_blocks_links_list" USING btree ("section_background_media_id");
  ALTER TABLE "page_blocks_hero" DROP COLUMN "section_margin_top";
  ALTER TABLE "page_blocks_hero" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "page_blocks_hero" DROP COLUMN "section_background_image_id";
  ALTER TABLE "page_blocks_text_section" DROP COLUMN "section_margin_top";
  ALTER TABLE "page_blocks_text_section" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "page_blocks_text_section" DROP COLUMN "section_background_image_id";
  ALTER TABLE "page_blocks_content" DROP COLUMN "section_margin_top";
  ALTER TABLE "page_blocks_content" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "page_blocks_content" DROP COLUMN "section_background_image_id";
  ALTER TABLE "page_blocks_faq" DROP COLUMN "section_margin_top";
  ALTER TABLE "page_blocks_faq" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "page_blocks_faq" DROP COLUMN "section_background_image_id";
  ALTER TABLE "page_blocks_testimonials_list" DROP COLUMN "section_margin_top";
  ALTER TABLE "page_blocks_testimonials_list" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "page_blocks_testimonials_list" DROP COLUMN "section_background_image_id";
  ALTER TABLE "page_blocks_cards_grid" DROP COLUMN "section_margin_top";
  ALTER TABLE "page_blocks_cards_grid" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "page_blocks_cards_grid" DROP COLUMN "section_background_image_id";
  ALTER TABLE "page_blocks_carousel" DROP COLUMN "section_margin_top";
  ALTER TABLE "page_blocks_carousel" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "page_blocks_carousel" DROP COLUMN "section_background_image_id";
  ALTER TABLE "page_blocks_logos" DROP COLUMN "section_margin_top";
  ALTER TABLE "page_blocks_logos" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "page_blocks_logos" DROP COLUMN "section_background_image_id";
  ALTER TABLE "page_blocks_links_list" DROP COLUMN "section_margin_top";
  ALTER TABLE "page_blocks_links_list" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "page_blocks_links_list" DROP COLUMN "section_background_image_id";
  ALTER TABLE "_page_v_blocks_hero" DROP COLUMN "section_margin_top";
  ALTER TABLE "_page_v_blocks_hero" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "_page_v_blocks_hero" DROP COLUMN "section_background_image_id";
  ALTER TABLE "_page_v_blocks_text_section" DROP COLUMN "section_margin_top";
  ALTER TABLE "_page_v_blocks_text_section" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "_page_v_blocks_text_section" DROP COLUMN "section_background_image_id";
  ALTER TABLE "_page_v_blocks_content" DROP COLUMN "section_margin_top";
  ALTER TABLE "_page_v_blocks_content" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "_page_v_blocks_content" DROP COLUMN "section_background_image_id";
  ALTER TABLE "_page_v_blocks_faq" DROP COLUMN "section_margin_top";
  ALTER TABLE "_page_v_blocks_faq" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "_page_v_blocks_faq" DROP COLUMN "section_background_image_id";
  ALTER TABLE "_page_v_blocks_testimonials_list" DROP COLUMN "section_margin_top";
  ALTER TABLE "_page_v_blocks_testimonials_list" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "_page_v_blocks_testimonials_list" DROP COLUMN "section_background_image_id";
  ALTER TABLE "_page_v_blocks_cards_grid" DROP COLUMN "section_margin_top";
  ALTER TABLE "_page_v_blocks_cards_grid" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "_page_v_blocks_cards_grid" DROP COLUMN "section_background_image_id";
  ALTER TABLE "_page_v_blocks_carousel" DROP COLUMN "section_margin_top";
  ALTER TABLE "_page_v_blocks_carousel" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "_page_v_blocks_carousel" DROP COLUMN "section_background_image_id";
  ALTER TABLE "_page_v_blocks_logos" DROP COLUMN "section_margin_top";
  ALTER TABLE "_page_v_blocks_logos" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "_page_v_blocks_logos" DROP COLUMN "section_background_image_id";
  ALTER TABLE "_page_v_blocks_links_list" DROP COLUMN "section_margin_top";
  ALTER TABLE "_page_v_blocks_links_list" DROP COLUMN "section_margin_bottom";
  ALTER TABLE "_page_v_blocks_links_list" DROP COLUMN "section_background_image_id";
  DROP TYPE "public"."enum_page_blocks_hero_section_margin_top";
  DROP TYPE "public"."enum_page_blocks_hero_section_margin_bottom";
  DROP TYPE "public"."enum_page_blocks_text_section_section_margin_top";
  DROP TYPE "public"."enum_page_blocks_text_section_section_margin_bottom";
  DROP TYPE "public"."enum_page_blocks_content_section_margin_top";
  DROP TYPE "public"."enum_page_blocks_content_section_margin_bottom";
  DROP TYPE "public"."enum_page_blocks_faq_section_margin_top";
  DROP TYPE "public"."enum_page_blocks_faq_section_margin_bottom";
  DROP TYPE "public"."enum_page_blocks_testimonials_list_section_margin_top";
  DROP TYPE "public"."enum_page_blocks_testimonials_list_section_margin_bottom";
  DROP TYPE "public"."enum_page_blocks_cards_grid_section_margin_top";
  DROP TYPE "public"."enum_page_blocks_cards_grid_section_margin_bottom";
  DROP TYPE "public"."enum_page_blocks_carousel_section_margin_top";
  DROP TYPE "public"."enum_page_blocks_carousel_section_margin_bottom";
  DROP TYPE "public"."enum_page_blocks_logos_section_margin_top";
  DROP TYPE "public"."enum_page_blocks_logos_section_margin_bottom";
  DROP TYPE "public"."enum_page_blocks_links_list_section_margin_top";
  DROP TYPE "public"."enum_page_blocks_links_list_section_margin_bottom";
  DROP TYPE "public"."enum__page_v_blocks_hero_section_margin_top";
  DROP TYPE "public"."enum__page_v_blocks_hero_section_margin_bottom";
  DROP TYPE "public"."enum__page_v_blocks_text_section_section_margin_top";
  DROP TYPE "public"."enum__page_v_blocks_text_section_section_margin_bottom";
  DROP TYPE "public"."enum__page_v_blocks_content_section_margin_top";
  DROP TYPE "public"."enum__page_v_blocks_content_section_margin_bottom";
  DROP TYPE "public"."enum__page_v_blocks_faq_section_margin_top";
  DROP TYPE "public"."enum__page_v_blocks_faq_section_margin_bottom";
  DROP TYPE "public"."enum__page_v_blocks_testimonials_list_section_margin_top";
  DROP TYPE "public"."enum__page_v_blocks_testimonials_list_section_margin_bottom";
  DROP TYPE "public"."enum__page_v_blocks_cards_grid_section_margin_top";
  DROP TYPE "public"."enum__page_v_blocks_cards_grid_section_margin_bottom";
  DROP TYPE "public"."enum__page_v_blocks_carousel_section_margin_top";
  DROP TYPE "public"."enum__page_v_blocks_carousel_section_margin_bottom";
  DROP TYPE "public"."enum__page_v_blocks_logos_section_margin_top";
  DROP TYPE "public"."enum__page_v_blocks_logos_section_margin_bottom";
  DROP TYPE "public"."enum__page_v_blocks_links_list_section_margin_top";
  DROP TYPE "public"."enum__page_v_blocks_links_list_section_margin_bottom";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_page_blocks_hero_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_hero_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_text_section_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_text_section_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_content_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_content_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_faq_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_faq_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_testimonials_list_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_testimonials_list_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_cards_grid_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_cards_grid_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_carousel_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_carousel_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_logos_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_logos_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_links_list_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum_page_blocks_links_list_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_hero_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_hero_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_text_section_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_text_section_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_content_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_content_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_faq_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_faq_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_testimonials_list_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_testimonials_list_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_cards_grid_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_cards_grid_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_carousel_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_carousel_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_logos_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_logos_section_margin_bottom" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_links_list_section_margin_top" AS ENUM('none', 'base', 'large');
  CREATE TYPE "public"."enum__page_v_blocks_links_list_section_margin_bottom" AS ENUM('none', 'base', 'large');
  ALTER TYPE "public"."enum_page_blocks_hero_section_padding_x" ADD VALUE 'large';
  ALTER TYPE "public"."enum_page_blocks_text_section_section_padding_x" ADD VALUE 'large';
  ALTER TYPE "public"."enum_page_blocks_content_section_padding_x" ADD VALUE 'large';
  ALTER TYPE "public"."enum_page_blocks_faq_section_padding_x" ADD VALUE 'large';
  ALTER TYPE "public"."enum_page_blocks_testimonials_list_section_padding_x" ADD VALUE 'large';
  ALTER TYPE "public"."enum_page_blocks_cards_grid_section_padding_x" ADD VALUE 'large';
  ALTER TYPE "public"."enum_page_blocks_carousel_section_padding_x" ADD VALUE 'large';
  ALTER TYPE "public"."enum_page_blocks_logos_section_padding_x" ADD VALUE 'large';
  ALTER TYPE "public"."enum_page_blocks_links_list_section_padding_x" ADD VALUE 'large';
  ALTER TYPE "public"."enum__page_v_blocks_hero_section_padding_x" ADD VALUE 'large';
  ALTER TYPE "public"."enum__page_v_blocks_text_section_section_padding_x" ADD VALUE 'large';
  ALTER TYPE "public"."enum__page_v_blocks_content_section_padding_x" ADD VALUE 'large';
  ALTER TYPE "public"."enum__page_v_blocks_faq_section_padding_x" ADD VALUE 'large';
  ALTER TYPE "public"."enum__page_v_blocks_testimonials_list_section_padding_x" ADD VALUE 'large';
  ALTER TYPE "public"."enum__page_v_blocks_cards_grid_section_padding_x" ADD VALUE 'large';
  ALTER TYPE "public"."enum__page_v_blocks_carousel_section_padding_x" ADD VALUE 'large';
  ALTER TYPE "public"."enum__page_v_blocks_logos_section_padding_x" ADD VALUE 'large';
  ALTER TYPE "public"."enum__page_v_blocks_links_list_section_padding_x" ADD VALUE 'large';
  ALTER TABLE "page_blocks_hero" DROP CONSTRAINT "page_blocks_hero_section_background_media_id_media_id_fk";
  
  ALTER TABLE "page_blocks_text_section" DROP CONSTRAINT "page_blocks_text_section_section_background_media_id_media_id_fk";
  
  ALTER TABLE "page_blocks_content" DROP CONSTRAINT "page_blocks_content_section_background_media_id_media_id_fk";
  
  ALTER TABLE "page_blocks_faq" DROP CONSTRAINT "page_blocks_faq_section_background_media_id_media_id_fk";
  
  ALTER TABLE "page_blocks_testimonials_list" DROP CONSTRAINT "page_blocks_testimonials_list_section_background_media_id_media_id_fk";
  
  ALTER TABLE "page_blocks_cards_grid" DROP CONSTRAINT "page_blocks_cards_grid_section_background_media_id_media_id_fk";
  
  ALTER TABLE "page_blocks_carousel" DROP CONSTRAINT "page_blocks_carousel_section_background_media_id_media_id_fk";
  
  ALTER TABLE "page_blocks_logos" DROP CONSTRAINT "page_blocks_logos_section_background_media_id_media_id_fk";
  
  ALTER TABLE "page_blocks_links_list" DROP CONSTRAINT "page_blocks_links_list_section_background_media_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_hero" DROP CONSTRAINT "_page_v_blocks_hero_section_background_media_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_text_section" DROP CONSTRAINT "_page_v_blocks_text_section_section_background_media_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_content" DROP CONSTRAINT "_page_v_blocks_content_section_background_media_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_faq" DROP CONSTRAINT "_page_v_blocks_faq_section_background_media_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_testimonials_list" DROP CONSTRAINT "_page_v_blocks_testimonials_list_section_background_media_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_cards_grid" DROP CONSTRAINT "_page_v_blocks_cards_grid_section_background_media_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_carousel" DROP CONSTRAINT "_page_v_blocks_carousel_section_background_media_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_logos" DROP CONSTRAINT "_page_v_blocks_logos_section_background_media_id_media_id_fk";
  
  ALTER TABLE "_page_v_blocks_links_list" DROP CONSTRAINT "_page_v_blocks_links_list_section_background_media_id_media_id_fk";
  
  ALTER TABLE "page_blocks_hero" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "page_blocks_hero" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_hero_section_max_width";
  CREATE TYPE "public"."enum_page_blocks_hero_section_max_width" AS ENUM('none', 'base', 'small');
  ALTER TABLE "page_blocks_hero" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum_page_blocks_hero_section_max_width";
  ALTER TABLE "page_blocks_hero" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum_page_blocks_hero_section_max_width" USING "section_max_width"::"public"."enum_page_blocks_hero_section_max_width";
  ALTER TABLE "page_blocks_text_section" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "page_blocks_text_section" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_text_section_section_max_width";
  CREATE TYPE "public"."enum_page_blocks_text_section_section_max_width" AS ENUM('none', 'base', 'small');
  ALTER TABLE "page_blocks_text_section" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum_page_blocks_text_section_section_max_width";
  ALTER TABLE "page_blocks_text_section" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum_page_blocks_text_section_section_max_width" USING "section_max_width"::"public"."enum_page_blocks_text_section_section_max_width";
  ALTER TABLE "page_blocks_content" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "page_blocks_content" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_content_section_max_width";
  CREATE TYPE "public"."enum_page_blocks_content_section_max_width" AS ENUM('none', 'base', 'small');
  ALTER TABLE "page_blocks_content" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum_page_blocks_content_section_max_width";
  ALTER TABLE "page_blocks_content" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum_page_blocks_content_section_max_width" USING "section_max_width"::"public"."enum_page_blocks_content_section_max_width";
  ALTER TABLE "page_blocks_faq" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "page_blocks_faq" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_faq_section_max_width";
  CREATE TYPE "public"."enum_page_blocks_faq_section_max_width" AS ENUM('none', 'base', 'small');
  ALTER TABLE "page_blocks_faq" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum_page_blocks_faq_section_max_width";
  ALTER TABLE "page_blocks_faq" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum_page_blocks_faq_section_max_width" USING "section_max_width"::"public"."enum_page_blocks_faq_section_max_width";
  ALTER TABLE "page_blocks_testimonials_list" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "page_blocks_testimonials_list" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_testimonials_list_section_max_width";
  CREATE TYPE "public"."enum_page_blocks_testimonials_list_section_max_width" AS ENUM('none', 'base', 'small');
  ALTER TABLE "page_blocks_testimonials_list" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum_page_blocks_testimonials_list_section_max_width";
  ALTER TABLE "page_blocks_testimonials_list" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum_page_blocks_testimonials_list_section_max_width" USING "section_max_width"::"public"."enum_page_blocks_testimonials_list_section_max_width";
  ALTER TABLE "page_blocks_cards_grid" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "page_blocks_cards_grid" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_cards_grid_section_max_width";
  CREATE TYPE "public"."enum_page_blocks_cards_grid_section_max_width" AS ENUM('none', 'base', 'small');
  ALTER TABLE "page_blocks_cards_grid" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum_page_blocks_cards_grid_section_max_width";
  ALTER TABLE "page_blocks_cards_grid" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum_page_blocks_cards_grid_section_max_width" USING "section_max_width"::"public"."enum_page_blocks_cards_grid_section_max_width";
  ALTER TABLE "page_blocks_carousel" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "page_blocks_carousel" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_carousel_section_max_width";
  CREATE TYPE "public"."enum_page_blocks_carousel_section_max_width" AS ENUM('none', 'base', 'small');
  ALTER TABLE "page_blocks_carousel" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum_page_blocks_carousel_section_max_width";
  ALTER TABLE "page_blocks_carousel" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum_page_blocks_carousel_section_max_width" USING "section_max_width"::"public"."enum_page_blocks_carousel_section_max_width";
  ALTER TABLE "page_blocks_logos" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "page_blocks_logos" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_logos_section_max_width";
  CREATE TYPE "public"."enum_page_blocks_logos_section_max_width" AS ENUM('none', 'base', 'small');
  ALTER TABLE "page_blocks_logos" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum_page_blocks_logos_section_max_width";
  ALTER TABLE "page_blocks_logos" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum_page_blocks_logos_section_max_width" USING "section_max_width"::"public"."enum_page_blocks_logos_section_max_width";
  ALTER TABLE "page_blocks_links_list" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "page_blocks_links_list" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum_page_blocks_links_list_section_max_width";
  CREATE TYPE "public"."enum_page_blocks_links_list_section_max_width" AS ENUM('none', 'base', 'small');
  ALTER TABLE "page_blocks_links_list" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum_page_blocks_links_list_section_max_width";
  ALTER TABLE "page_blocks_links_list" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum_page_blocks_links_list_section_max_width" USING "section_max_width"::"public"."enum_page_blocks_links_list_section_max_width";
  ALTER TABLE "_page_v_blocks_hero" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_hero" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_hero_section_max_width";
  CREATE TYPE "public"."enum__page_v_blocks_hero_section_max_width" AS ENUM('none', 'base', 'small');
  ALTER TABLE "_page_v_blocks_hero" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum__page_v_blocks_hero_section_max_width";
  ALTER TABLE "_page_v_blocks_hero" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum__page_v_blocks_hero_section_max_width" USING "section_max_width"::"public"."enum__page_v_blocks_hero_section_max_width";
  ALTER TABLE "_page_v_blocks_text_section" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_text_section" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_text_section_section_max_width";
  CREATE TYPE "public"."enum__page_v_blocks_text_section_section_max_width" AS ENUM('none', 'base', 'small');
  ALTER TABLE "_page_v_blocks_text_section" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum__page_v_blocks_text_section_section_max_width";
  ALTER TABLE "_page_v_blocks_text_section" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum__page_v_blocks_text_section_section_max_width" USING "section_max_width"::"public"."enum__page_v_blocks_text_section_section_max_width";
  ALTER TABLE "_page_v_blocks_content" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_content" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_content_section_max_width";
  CREATE TYPE "public"."enum__page_v_blocks_content_section_max_width" AS ENUM('none', 'base', 'small');
  ALTER TABLE "_page_v_blocks_content" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum__page_v_blocks_content_section_max_width";
  ALTER TABLE "_page_v_blocks_content" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum__page_v_blocks_content_section_max_width" USING "section_max_width"::"public"."enum__page_v_blocks_content_section_max_width";
  ALTER TABLE "_page_v_blocks_faq" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_faq" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_faq_section_max_width";
  CREATE TYPE "public"."enum__page_v_blocks_faq_section_max_width" AS ENUM('none', 'base', 'small');
  ALTER TABLE "_page_v_blocks_faq" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum__page_v_blocks_faq_section_max_width";
  ALTER TABLE "_page_v_blocks_faq" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum__page_v_blocks_faq_section_max_width" USING "section_max_width"::"public"."enum__page_v_blocks_faq_section_max_width";
  ALTER TABLE "_page_v_blocks_testimonials_list" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_testimonials_list" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_testimonials_list_section_max_width";
  CREATE TYPE "public"."enum__page_v_blocks_testimonials_list_section_max_width" AS ENUM('none', 'base', 'small');
  ALTER TABLE "_page_v_blocks_testimonials_list" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum__page_v_blocks_testimonials_list_section_max_width";
  ALTER TABLE "_page_v_blocks_testimonials_list" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum__page_v_blocks_testimonials_list_section_max_width" USING "section_max_width"::"public"."enum__page_v_blocks_testimonials_list_section_max_width";
  ALTER TABLE "_page_v_blocks_cards_grid" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_cards_grid" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_cards_grid_section_max_width";
  CREATE TYPE "public"."enum__page_v_blocks_cards_grid_section_max_width" AS ENUM('none', 'base', 'small');
  ALTER TABLE "_page_v_blocks_cards_grid" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum__page_v_blocks_cards_grid_section_max_width";
  ALTER TABLE "_page_v_blocks_cards_grid" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum__page_v_blocks_cards_grid_section_max_width" USING "section_max_width"::"public"."enum__page_v_blocks_cards_grid_section_max_width";
  ALTER TABLE "_page_v_blocks_carousel" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_carousel" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_carousel_section_max_width";
  CREATE TYPE "public"."enum__page_v_blocks_carousel_section_max_width" AS ENUM('none', 'base', 'small');
  ALTER TABLE "_page_v_blocks_carousel" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum__page_v_blocks_carousel_section_max_width";
  ALTER TABLE "_page_v_blocks_carousel" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum__page_v_blocks_carousel_section_max_width" USING "section_max_width"::"public"."enum__page_v_blocks_carousel_section_max_width";
  ALTER TABLE "_page_v_blocks_logos" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_logos" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_logos_section_max_width";
  CREATE TYPE "public"."enum__page_v_blocks_logos_section_max_width" AS ENUM('none', 'base', 'small');
  ALTER TABLE "_page_v_blocks_logos" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum__page_v_blocks_logos_section_max_width";
  ALTER TABLE "_page_v_blocks_logos" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum__page_v_blocks_logos_section_max_width" USING "section_max_width"::"public"."enum__page_v_blocks_logos_section_max_width";
  ALTER TABLE "_page_v_blocks_links_list" ALTER COLUMN "section_max_width" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_links_list" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::text;
  DROP TYPE "public"."enum__page_v_blocks_links_list_section_max_width";
  CREATE TYPE "public"."enum__page_v_blocks_links_list_section_max_width" AS ENUM('none', 'base', 'small');
  ALTER TABLE "_page_v_blocks_links_list" ALTER COLUMN "section_max_width" SET DEFAULT 'base'::"public"."enum__page_v_blocks_links_list_section_max_width";
  ALTER TABLE "_page_v_blocks_links_list" ALTER COLUMN "section_max_width" SET DATA TYPE "public"."enum__page_v_blocks_links_list_section_max_width" USING "section_max_width"::"public"."enum__page_v_blocks_links_list_section_max_width";
  DROP INDEX "page_blocks_hero_section_background_section_background_m_idx";
  DROP INDEX "page_blocks_text_section_section_background_section_back_idx";
  DROP INDEX "page_blocks_content_section_background_section_backgroun_idx";
  DROP INDEX "page_blocks_faq_section_background_section_background_me_idx";
  DROP INDEX "page_blocks_testimonials_list_section_background_section_idx";
  DROP INDEX "page_blocks_cards_grid_section_background_section_backgr_idx";
  DROP INDEX "page_blocks_carousel_section_background_section_backgrou_idx";
  DROP INDEX "page_blocks_logos_section_background_section_background__idx";
  DROP INDEX "page_blocks_links_list_section_background_section_backgr_idx";
  DROP INDEX "_page_v_blocks_hero_section_background_section_backgroun_idx";
  DROP INDEX "_page_v_blocks_text_section_section_background_section_b_idx";
  DROP INDEX "_page_v_blocks_content_section_background_section_backgr_idx";
  DROP INDEX "_page_v_blocks_faq_section_background_section_background_idx";
  DROP INDEX "_page_v_blocks_testimonials_list_section_background_sect_idx";
  DROP INDEX "_page_v_blocks_cards_grid_section_background_section_bac_idx";
  DROP INDEX "_page_v_blocks_carousel_section_background_section_backg_idx";
  DROP INDEX "_page_v_blocks_logos_section_background_section_backgrou_idx";
  DROP INDEX "_page_v_blocks_links_list_section_background_section_bac_idx";
  ALTER TABLE "page_blocks_hero" ADD COLUMN "section_margin_top" "enum_page_blocks_hero_section_margin_top" DEFAULT 'base';
  ALTER TABLE "page_blocks_hero" ADD COLUMN "section_margin_bottom" "enum_page_blocks_hero_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "page_blocks_hero" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "page_blocks_text_section" ADD COLUMN "section_margin_top" "enum_page_blocks_text_section_section_margin_top" DEFAULT 'base';
  ALTER TABLE "page_blocks_text_section" ADD COLUMN "section_margin_bottom" "enum_page_blocks_text_section_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "page_blocks_text_section" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "page_blocks_content" ADD COLUMN "section_margin_top" "enum_page_blocks_content_section_margin_top" DEFAULT 'base';
  ALTER TABLE "page_blocks_content" ADD COLUMN "section_margin_bottom" "enum_page_blocks_content_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "page_blocks_content" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "page_blocks_faq" ADD COLUMN "section_margin_top" "enum_page_blocks_faq_section_margin_top" DEFAULT 'base';
  ALTER TABLE "page_blocks_faq" ADD COLUMN "section_margin_bottom" "enum_page_blocks_faq_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "page_blocks_faq" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "page_blocks_testimonials_list" ADD COLUMN "section_margin_top" "enum_page_blocks_testimonials_list_section_margin_top" DEFAULT 'base';
  ALTER TABLE "page_blocks_testimonials_list" ADD COLUMN "section_margin_bottom" "enum_page_blocks_testimonials_list_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "page_blocks_testimonials_list" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "page_blocks_cards_grid" ADD COLUMN "section_margin_top" "enum_page_blocks_cards_grid_section_margin_top" DEFAULT 'base';
  ALTER TABLE "page_blocks_cards_grid" ADD COLUMN "section_margin_bottom" "enum_page_blocks_cards_grid_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "page_blocks_cards_grid" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "page_blocks_carousel" ADD COLUMN "section_margin_top" "enum_page_blocks_carousel_section_margin_top" DEFAULT 'base';
  ALTER TABLE "page_blocks_carousel" ADD COLUMN "section_margin_bottom" "enum_page_blocks_carousel_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "page_blocks_carousel" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "page_blocks_logos" ADD COLUMN "section_margin_top" "enum_page_blocks_logos_section_margin_top" DEFAULT 'base';
  ALTER TABLE "page_blocks_logos" ADD COLUMN "section_margin_bottom" "enum_page_blocks_logos_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "page_blocks_logos" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "page_blocks_links_list" ADD COLUMN "section_margin_top" "enum_page_blocks_links_list_section_margin_top" DEFAULT 'base';
  ALTER TABLE "page_blocks_links_list" ADD COLUMN "section_margin_bottom" "enum_page_blocks_links_list_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "page_blocks_links_list" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "_page_v_blocks_hero" ADD COLUMN "section_margin_top" "enum__page_v_blocks_hero_section_margin_top" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_hero" ADD COLUMN "section_margin_bottom" "enum__page_v_blocks_hero_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_hero" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "_page_v_blocks_text_section" ADD COLUMN "section_margin_top" "enum__page_v_blocks_text_section_section_margin_top" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_text_section" ADD COLUMN "section_margin_bottom" "enum__page_v_blocks_text_section_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_text_section" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "_page_v_blocks_content" ADD COLUMN "section_margin_top" "enum__page_v_blocks_content_section_margin_top" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_content" ADD COLUMN "section_margin_bottom" "enum__page_v_blocks_content_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_content" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "_page_v_blocks_faq" ADD COLUMN "section_margin_top" "enum__page_v_blocks_faq_section_margin_top" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_faq" ADD COLUMN "section_margin_bottom" "enum__page_v_blocks_faq_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_faq" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "_page_v_blocks_testimonials_list" ADD COLUMN "section_margin_top" "enum__page_v_blocks_testimonials_list_section_margin_top" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_testimonials_list" ADD COLUMN "section_margin_bottom" "enum__page_v_blocks_testimonials_list_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_testimonials_list" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "_page_v_blocks_cards_grid" ADD COLUMN "section_margin_top" "enum__page_v_blocks_cards_grid_section_margin_top" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_cards_grid" ADD COLUMN "section_margin_bottom" "enum__page_v_blocks_cards_grid_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_cards_grid" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "_page_v_blocks_carousel" ADD COLUMN "section_margin_top" "enum__page_v_blocks_carousel_section_margin_top" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_carousel" ADD COLUMN "section_margin_bottom" "enum__page_v_blocks_carousel_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_carousel" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "_page_v_blocks_logos" ADD COLUMN "section_margin_top" "enum__page_v_blocks_logos_section_margin_top" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_logos" ADD COLUMN "section_margin_bottom" "enum__page_v_blocks_logos_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_logos" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "_page_v_blocks_links_list" ADD COLUMN "section_margin_top" "enum__page_v_blocks_links_list_section_margin_top" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_links_list" ADD COLUMN "section_margin_bottom" "enum__page_v_blocks_links_list_section_margin_bottom" DEFAULT 'base';
  ALTER TABLE "_page_v_blocks_links_list" ADD COLUMN "section_background_image_id" integer;
  ALTER TABLE "page_blocks_hero" ADD CONSTRAINT "page_blocks_hero_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_text_section" ADD CONSTRAINT "page_blocks_text_section_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_content" ADD CONSTRAINT "page_blocks_content_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_faq" ADD CONSTRAINT "page_blocks_faq_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_testimonials_list" ADD CONSTRAINT "page_blocks_testimonials_list_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_cards_grid" ADD CONSTRAINT "page_blocks_cards_grid_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_carousel" ADD CONSTRAINT "page_blocks_carousel_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_logos" ADD CONSTRAINT "page_blocks_logos_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "page_blocks_links_list" ADD CONSTRAINT "page_blocks_links_list_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_hero" ADD CONSTRAINT "_page_v_blocks_hero_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_text_section" ADD CONSTRAINT "_page_v_blocks_text_section_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_content" ADD CONSTRAINT "_page_v_blocks_content_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_faq" ADD CONSTRAINT "_page_v_blocks_faq_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_testimonials_list" ADD CONSTRAINT "_page_v_blocks_testimonials_list_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_cards_grid" ADD CONSTRAINT "_page_v_blocks_cards_grid_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_carousel" ADD CONSTRAINT "_page_v_blocks_carousel_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_logos" ADD CONSTRAINT "_page_v_blocks_logos_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_page_v_blocks_links_list" ADD CONSTRAINT "_page_v_blocks_links_list_section_background_image_id_media_id_fk" FOREIGN KEY ("section_background_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "page_blocks_hero_section_section_background_image_idx" ON "page_blocks_hero" USING btree ("section_background_image_id");
  CREATE INDEX "page_blocks_text_section_section_section_background_imag_idx" ON "page_blocks_text_section" USING btree ("section_background_image_id");
  CREATE INDEX "page_blocks_content_section_section_background_image_idx" ON "page_blocks_content" USING btree ("section_background_image_id");
  CREATE INDEX "page_blocks_faq_section_section_background_image_idx" ON "page_blocks_faq" USING btree ("section_background_image_id");
  CREATE INDEX "page_blocks_testimonials_list_section_section_background_idx" ON "page_blocks_testimonials_list" USING btree ("section_background_image_id");
  CREATE INDEX "page_blocks_cards_grid_section_section_background_image_idx" ON "page_blocks_cards_grid" USING btree ("section_background_image_id");
  CREATE INDEX "page_blocks_carousel_section_section_background_image_idx" ON "page_blocks_carousel" USING btree ("section_background_image_id");
  CREATE INDEX "page_blocks_logos_section_section_background_image_idx" ON "page_blocks_logos" USING btree ("section_background_image_id");
  CREATE INDEX "page_blocks_links_list_section_section_background_image_idx" ON "page_blocks_links_list" USING btree ("section_background_image_id");
  CREATE INDEX "_page_v_blocks_hero_section_section_background_image_idx" ON "_page_v_blocks_hero" USING btree ("section_background_image_id");
  CREATE INDEX "_page_v_blocks_text_section_section_section_background_i_idx" ON "_page_v_blocks_text_section" USING btree ("section_background_image_id");
  CREATE INDEX "_page_v_blocks_content_section_section_background_image_idx" ON "_page_v_blocks_content" USING btree ("section_background_image_id");
  CREATE INDEX "_page_v_blocks_faq_section_section_background_image_idx" ON "_page_v_blocks_faq" USING btree ("section_background_image_id");
  CREATE INDEX "_page_v_blocks_testimonials_list_section_section_backgro_idx" ON "_page_v_blocks_testimonials_list" USING btree ("section_background_image_id");
  CREATE INDEX "_page_v_blocks_cards_grid_section_section_background_ima_idx" ON "_page_v_blocks_cards_grid" USING btree ("section_background_image_id");
  CREATE INDEX "_page_v_blocks_carousel_section_section_background_image_idx" ON "_page_v_blocks_carousel" USING btree ("section_background_image_id");
  CREATE INDEX "_page_v_blocks_logos_section_section_background_image_idx" ON "_page_v_blocks_logos" USING btree ("section_background_image_id");
  CREATE INDEX "_page_v_blocks_links_list_section_section_background_ima_idx" ON "_page_v_blocks_links_list" USING btree ("section_background_image_id");
  ALTER TABLE "page_blocks_hero" DROP COLUMN "section_background_media_id";
  ALTER TABLE "page_blocks_hero" DROP COLUMN "section_background_overlay";
  ALTER TABLE "page_blocks_hero" DROP COLUMN "section_background_opacity";
  ALTER TABLE "page_blocks_text_section" DROP COLUMN "section_background_media_id";
  ALTER TABLE "page_blocks_text_section" DROP COLUMN "section_background_overlay";
  ALTER TABLE "page_blocks_text_section" DROP COLUMN "section_background_opacity";
  ALTER TABLE "page_blocks_content" DROP COLUMN "section_background_media_id";
  ALTER TABLE "page_blocks_content" DROP COLUMN "section_background_overlay";
  ALTER TABLE "page_blocks_content" DROP COLUMN "section_background_opacity";
  ALTER TABLE "page_blocks_faq" DROP COLUMN "section_background_media_id";
  ALTER TABLE "page_blocks_faq" DROP COLUMN "section_background_overlay";
  ALTER TABLE "page_blocks_faq" DROP COLUMN "section_background_opacity";
  ALTER TABLE "page_blocks_testimonials_list" DROP COLUMN "section_background_media_id";
  ALTER TABLE "page_blocks_testimonials_list" DROP COLUMN "section_background_overlay";
  ALTER TABLE "page_blocks_testimonials_list" DROP COLUMN "section_background_opacity";
  ALTER TABLE "page_blocks_cards_grid" DROP COLUMN "section_background_media_id";
  ALTER TABLE "page_blocks_cards_grid" DROP COLUMN "section_background_overlay";
  ALTER TABLE "page_blocks_cards_grid" DROP COLUMN "section_background_opacity";
  ALTER TABLE "page_blocks_carousel" DROP COLUMN "section_background_media_id";
  ALTER TABLE "page_blocks_carousel" DROP COLUMN "section_background_overlay";
  ALTER TABLE "page_blocks_carousel" DROP COLUMN "section_background_opacity";
  ALTER TABLE "page_blocks_logos" DROP COLUMN "section_background_media_id";
  ALTER TABLE "page_blocks_logos" DROP COLUMN "section_background_overlay";
  ALTER TABLE "page_blocks_logos" DROP COLUMN "section_background_opacity";
  ALTER TABLE "page_blocks_links_list" DROP COLUMN "section_background_media_id";
  ALTER TABLE "page_blocks_links_list" DROP COLUMN "section_background_overlay";
  ALTER TABLE "page_blocks_links_list" DROP COLUMN "section_background_opacity";
  ALTER TABLE "_page_v_blocks_hero" DROP COLUMN "section_background_media_id";
  ALTER TABLE "_page_v_blocks_hero" DROP COLUMN "section_background_overlay";
  ALTER TABLE "_page_v_blocks_hero" DROP COLUMN "section_background_opacity";
  ALTER TABLE "_page_v_blocks_text_section" DROP COLUMN "section_background_media_id";
  ALTER TABLE "_page_v_blocks_text_section" DROP COLUMN "section_background_overlay";
  ALTER TABLE "_page_v_blocks_text_section" DROP COLUMN "section_background_opacity";
  ALTER TABLE "_page_v_blocks_content" DROP COLUMN "section_background_media_id";
  ALTER TABLE "_page_v_blocks_content" DROP COLUMN "section_background_overlay";
  ALTER TABLE "_page_v_blocks_content" DROP COLUMN "section_background_opacity";
  ALTER TABLE "_page_v_blocks_faq" DROP COLUMN "section_background_media_id";
  ALTER TABLE "_page_v_blocks_faq" DROP COLUMN "section_background_overlay";
  ALTER TABLE "_page_v_blocks_faq" DROP COLUMN "section_background_opacity";
  ALTER TABLE "_page_v_blocks_testimonials_list" DROP COLUMN "section_background_media_id";
  ALTER TABLE "_page_v_blocks_testimonials_list" DROP COLUMN "section_background_overlay";
  ALTER TABLE "_page_v_blocks_testimonials_list" DROP COLUMN "section_background_opacity";
  ALTER TABLE "_page_v_blocks_cards_grid" DROP COLUMN "section_background_media_id";
  ALTER TABLE "_page_v_blocks_cards_grid" DROP COLUMN "section_background_overlay";
  ALTER TABLE "_page_v_blocks_cards_grid" DROP COLUMN "section_background_opacity";
  ALTER TABLE "_page_v_blocks_carousel" DROP COLUMN "section_background_media_id";
  ALTER TABLE "_page_v_blocks_carousel" DROP COLUMN "section_background_overlay";
  ALTER TABLE "_page_v_blocks_carousel" DROP COLUMN "section_background_opacity";
  ALTER TABLE "_page_v_blocks_logos" DROP COLUMN "section_background_media_id";
  ALTER TABLE "_page_v_blocks_logos" DROP COLUMN "section_background_overlay";
  ALTER TABLE "_page_v_blocks_logos" DROP COLUMN "section_background_opacity";
  ALTER TABLE "_page_v_blocks_links_list" DROP COLUMN "section_background_media_id";
  ALTER TABLE "_page_v_blocks_links_list" DROP COLUMN "section_background_overlay";
  ALTER TABLE "_page_v_blocks_links_list" DROP COLUMN "section_background_opacity";
  DROP TYPE "public"."sec_bg_ovrly";`)
}
