import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_page_blocks_hero_actions_custom_page" AS ENUM('blog');
  CREATE TYPE "public"."enum_page_blocks_cards_grid_items_link_custom_page" AS ENUM('blog');
  CREATE TYPE "public"."enum_page_blocks_logos_items_link_custom_page" AS ENUM('blog');
  CREATE TYPE "public"."enum_page_blocks_links_list_links_link_custom_page" AS ENUM('blog');
  CREATE TYPE "public"."enum__page_v_blocks_hero_actions_custom_page" AS ENUM('blog');
  CREATE TYPE "public"."enum__page_v_blocks_cards_grid_items_link_custom_page" AS ENUM('blog');
  CREATE TYPE "public"."enum__page_v_blocks_logos_items_link_custom_page" AS ENUM('blog');
  CREATE TYPE "public"."enum__page_v_blocks_links_list_links_link_custom_page" AS ENUM('blog');
  CREATE TYPE "public"."enum_header_nav_items_link_custom_page" AS ENUM('blog');
  CREATE TYPE "public"."enum__header_v_version_nav_items_link_custom_page" AS ENUM('blog');
  CREATE TYPE "public"."enum_footer_links_link_custom_page" AS ENUM('blog');
  CREATE TYPE "public"."enum__footer_v_version_links_link_custom_page" AS ENUM('blog');
  CREATE TYPE "public"."enum_presets_hero_actions_custom_page" AS ENUM('blog');
  ALTER TYPE "public"."enum_page_blocks_hero_actions_type" ADD VALUE 'customPage';
  ALTER TYPE "public"."enum_page_blocks_cards_grid_items_link_type" ADD VALUE 'customPage';
  ALTER TYPE "public"."enum_page_blocks_logos_items_link_type" ADD VALUE 'customPage';
  ALTER TYPE "public"."enum_page_blocks_links_list_links_link_type" ADD VALUE 'customPage';
  ALTER TYPE "public"."enum__page_v_blocks_hero_actions_type" ADD VALUE 'customPage';
  ALTER TYPE "public"."enum__page_v_blocks_cards_grid_items_link_type" ADD VALUE 'customPage';
  ALTER TYPE "public"."enum__page_v_blocks_logos_items_link_type" ADD VALUE 'customPage';
  ALTER TYPE "public"."enum__page_v_blocks_links_list_links_link_type" ADD VALUE 'customPage';
  ALTER TYPE "public"."enum_header_nav_items_link_type" ADD VALUE 'customPage';
  ALTER TYPE "public"."enum__header_v_version_nav_items_link_type" ADD VALUE 'customPage';
  ALTER TYPE "public"."enum_footer_links_link_type" ADD VALUE 'customPage';
  ALTER TYPE "public"."enum__footer_v_version_links_link_type" ADD VALUE 'customPage';
  ALTER TYPE "public"."enum_presets_hero_actions_type" ADD VALUE 'customPage';
  ALTER TABLE "page_blocks_hero_actions" ADD COLUMN "custom_page" "enum_page_blocks_hero_actions_custom_page";
  ALTER TABLE "page_blocks_cards_grid_items" ADD COLUMN "link_custom_page" "enum_page_blocks_cards_grid_items_link_custom_page";
  ALTER TABLE "page_blocks_logos_items" ADD COLUMN "link_custom_page" "enum_page_blocks_logos_items_link_custom_page";
  ALTER TABLE "page_blocks_links_list_links" ADD COLUMN "link_custom_page" "enum_page_blocks_links_list_links_link_custom_page";
  ALTER TABLE "_page_v_blocks_hero_actions" ADD COLUMN "custom_page" "enum__page_v_blocks_hero_actions_custom_page";
  ALTER TABLE "_page_v_blocks_cards_grid_items" ADD COLUMN "link_custom_page" "enum__page_v_blocks_cards_grid_items_link_custom_page";
  ALTER TABLE "_page_v_blocks_logos_items" ADD COLUMN "link_custom_page" "enum__page_v_blocks_logos_items_link_custom_page";
  ALTER TABLE "_page_v_blocks_links_list_links" ADD COLUMN "link_custom_page" "enum__page_v_blocks_links_list_links_link_custom_page";
  ALTER TABLE "header_nav_items" ADD COLUMN "link_custom_page" "enum_header_nav_items_link_custom_page";
  ALTER TABLE "_header_v_version_nav_items" ADD COLUMN "link_custom_page" "enum__header_v_version_nav_items_link_custom_page";
  ALTER TABLE "footer_links" ADD COLUMN "link_custom_page" "enum_footer_links_link_custom_page";
  ALTER TABLE "_footer_v_version_links" ADD COLUMN "link_custom_page" "enum__footer_v_version_links_link_custom_page";
  ALTER TABLE "presets_hero_actions" ADD COLUMN "custom_page" "enum_presets_hero_actions_custom_page";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "page_blocks_hero_actions" ALTER COLUMN "type" SET DATA TYPE text;
  ALTER TABLE "page_blocks_hero_actions" ALTER COLUMN "type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_page_blocks_hero_actions_type";
  CREATE TYPE "public"."enum_page_blocks_hero_actions_type" AS ENUM('reference', 'custom');
  ALTER TABLE "page_blocks_hero_actions" ALTER COLUMN "type" SET DEFAULT 'reference'::"public"."enum_page_blocks_hero_actions_type";
  ALTER TABLE "page_blocks_hero_actions" ALTER COLUMN "type" SET DATA TYPE "public"."enum_page_blocks_hero_actions_type" USING "type"::"public"."enum_page_blocks_hero_actions_type";
  ALTER TABLE "page_blocks_cards_grid_items" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "page_blocks_cards_grid_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_page_blocks_cards_grid_items_link_type";
  CREATE TYPE "public"."enum_page_blocks_cards_grid_items_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "page_blocks_cards_grid_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_page_blocks_cards_grid_items_link_type";
  ALTER TABLE "page_blocks_cards_grid_items" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_page_blocks_cards_grid_items_link_type" USING "link_type"::"public"."enum_page_blocks_cards_grid_items_link_type";
  ALTER TABLE "page_blocks_logos_items" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "page_blocks_logos_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_page_blocks_logos_items_link_type";
  CREATE TYPE "public"."enum_page_blocks_logos_items_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "page_blocks_logos_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_page_blocks_logos_items_link_type";
  ALTER TABLE "page_blocks_logos_items" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_page_blocks_logos_items_link_type" USING "link_type"::"public"."enum_page_blocks_logos_items_link_type";
  ALTER TABLE "page_blocks_links_list_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "page_blocks_links_list_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_page_blocks_links_list_links_link_type";
  CREATE TYPE "public"."enum_page_blocks_links_list_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "page_blocks_links_list_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_page_blocks_links_list_links_link_type";
  ALTER TABLE "page_blocks_links_list_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_page_blocks_links_list_links_link_type" USING "link_type"::"public"."enum_page_blocks_links_list_links_link_type";
  ALTER TABLE "_page_v_blocks_hero_actions" ALTER COLUMN "type" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_hero_actions" ALTER COLUMN "type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__page_v_blocks_hero_actions_type";
  CREATE TYPE "public"."enum__page_v_blocks_hero_actions_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_page_v_blocks_hero_actions" ALTER COLUMN "type" SET DEFAULT 'reference'::"public"."enum__page_v_blocks_hero_actions_type";
  ALTER TABLE "_page_v_blocks_hero_actions" ALTER COLUMN "type" SET DATA TYPE "public"."enum__page_v_blocks_hero_actions_type" USING "type"::"public"."enum__page_v_blocks_hero_actions_type";
  ALTER TABLE "_page_v_blocks_cards_grid_items" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_cards_grid_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__page_v_blocks_cards_grid_items_link_type";
  CREATE TYPE "public"."enum__page_v_blocks_cards_grid_items_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_page_v_blocks_cards_grid_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__page_v_blocks_cards_grid_items_link_type";
  ALTER TABLE "_page_v_blocks_cards_grid_items" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__page_v_blocks_cards_grid_items_link_type" USING "link_type"::"public"."enum__page_v_blocks_cards_grid_items_link_type";
  ALTER TABLE "_page_v_blocks_logos_items" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_logos_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__page_v_blocks_logos_items_link_type";
  CREATE TYPE "public"."enum__page_v_blocks_logos_items_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_page_v_blocks_logos_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__page_v_blocks_logos_items_link_type";
  ALTER TABLE "_page_v_blocks_logos_items" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__page_v_blocks_logos_items_link_type" USING "link_type"::"public"."enum__page_v_blocks_logos_items_link_type";
  ALTER TABLE "_page_v_blocks_links_list_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_page_v_blocks_links_list_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__page_v_blocks_links_list_links_link_type";
  CREATE TYPE "public"."enum__page_v_blocks_links_list_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_page_v_blocks_links_list_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__page_v_blocks_links_list_links_link_type";
  ALTER TABLE "_page_v_blocks_links_list_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__page_v_blocks_links_list_links_link_type" USING "link_type"::"public"."enum__page_v_blocks_links_list_links_link_type";
  ALTER TABLE "header_nav_items" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "header_nav_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_header_nav_items_link_type";
  CREATE TYPE "public"."enum_header_nav_items_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "header_nav_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_header_nav_items_link_type";
  ALTER TABLE "header_nav_items" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_header_nav_items_link_type" USING "link_type"::"public"."enum_header_nav_items_link_type";
  ALTER TABLE "_header_v_version_nav_items" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_header_v_version_nav_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__header_v_version_nav_items_link_type";
  CREATE TYPE "public"."enum__header_v_version_nav_items_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_header_v_version_nav_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__header_v_version_nav_items_link_type";
  ALTER TABLE "_header_v_version_nav_items" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__header_v_version_nav_items_link_type" USING "link_type"::"public"."enum__header_v_version_nav_items_link_type";
  ALTER TABLE "footer_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "footer_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_footer_links_link_type";
  CREATE TYPE "public"."enum_footer_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "footer_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_footer_links_link_type";
  ALTER TABLE "footer_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_footer_links_link_type" USING "link_type"::"public"."enum_footer_links_link_type";
  ALTER TABLE "_footer_v_version_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_footer_v_version_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__footer_v_version_links_link_type";
  CREATE TYPE "public"."enum__footer_v_version_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_footer_v_version_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__footer_v_version_links_link_type";
  ALTER TABLE "_footer_v_version_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__footer_v_version_links_link_type" USING "link_type"::"public"."enum__footer_v_version_links_link_type";
  ALTER TABLE "presets_hero_actions" ALTER COLUMN "type" SET DATA TYPE text;
  ALTER TABLE "presets_hero_actions" ALTER COLUMN "type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_presets_hero_actions_type";
  CREATE TYPE "public"."enum_presets_hero_actions_type" AS ENUM('reference', 'custom');
  ALTER TABLE "presets_hero_actions" ALTER COLUMN "type" SET DEFAULT 'reference'::"public"."enum_presets_hero_actions_type";
  ALTER TABLE "presets_hero_actions" ALTER COLUMN "type" SET DATA TYPE "public"."enum_presets_hero_actions_type" USING "type"::"public"."enum_presets_hero_actions_type";
  ALTER TABLE "page_blocks_hero_actions" DROP COLUMN "custom_page";
  ALTER TABLE "page_blocks_cards_grid_items" DROP COLUMN "link_custom_page";
  ALTER TABLE "page_blocks_logos_items" DROP COLUMN "link_custom_page";
  ALTER TABLE "page_blocks_links_list_links" DROP COLUMN "link_custom_page";
  ALTER TABLE "_page_v_blocks_hero_actions" DROP COLUMN "custom_page";
  ALTER TABLE "_page_v_blocks_cards_grid_items" DROP COLUMN "link_custom_page";
  ALTER TABLE "_page_v_blocks_logos_items" DROP COLUMN "link_custom_page";
  ALTER TABLE "_page_v_blocks_links_list_links" DROP COLUMN "link_custom_page";
  ALTER TABLE "header_nav_items" DROP COLUMN "link_custom_page";
  ALTER TABLE "_header_v_version_nav_items" DROP COLUMN "link_custom_page";
  ALTER TABLE "footer_links" DROP COLUMN "link_custom_page";
  ALTER TABLE "_footer_v_version_links" DROP COLUMN "link_custom_page";
  ALTER TABLE "presets_hero_actions" DROP COLUMN "custom_page";
  DROP TYPE "public"."enum_page_blocks_hero_actions_custom_page";
  DROP TYPE "public"."enum_page_blocks_cards_grid_items_link_custom_page";
  DROP TYPE "public"."enum_page_blocks_logos_items_link_custom_page";
  DROP TYPE "public"."enum_page_blocks_links_list_links_link_custom_page";
  DROP TYPE "public"."enum__page_v_blocks_hero_actions_custom_page";
  DROP TYPE "public"."enum__page_v_blocks_cards_grid_items_link_custom_page";
  DROP TYPE "public"."enum__page_v_blocks_logos_items_link_custom_page";
  DROP TYPE "public"."enum__page_v_blocks_links_list_links_link_custom_page";
  DROP TYPE "public"."enum_header_nav_items_link_custom_page";
  DROP TYPE "public"."enum__header_v_version_nav_items_link_custom_page";
  DROP TYPE "public"."enum_footer_links_link_custom_page";
  DROP TYPE "public"."enum__footer_v_version_links_link_custom_page";
  DROP TYPE "public"."enum_presets_hero_actions_custom_page";`)
}
