import { existsSync } from "node:fs";
import path from "node:path";

import { withPayload } from "@payloadcms/next/withPayload";
import createNextIntlPlugin from "next-intl/plugin";

const __dirname = import.meta.dirname;

const THIRTY_DAYS_IN_SECONDS = 60 * 60 * 24 * 30;

// The full legacy-URL map is generated by the CT seed into a git-ignored file (old slugs carry the
// client's name, which must not enter the public repo); without it the committed extras are used.
const LEGACY_LOCAL = path.resolve(__dirname, "src/lib/redirects/legacy.local.json");
const LEGACY_MAP = existsSync(LEGACY_LOCAL)
  ? LEGACY_LOCAL
  : path.resolve(__dirname, "src/lib/redirects/legacy.json");

/** @type {import('next').NextConfig} */
const nextConfig = {
  // Docker image only (Dockerfile sets NEXT_OUTPUT=standalone): a self-contained server traced from
  // the monorepo root, so it lands at .next/standalone/apps/cms/server.js. Vercel keeps its default.
  ...(process.env.NEXT_OUTPUT === "standalone" && {
    output: "standalone",
    outputFileTracingRoot: path.resolve(__dirname, "../.."),
  }),
  turbopack: {
    resolveAlias: {
      "@ct/legacy-map": path.relative(__dirname, LEGACY_MAP).replace(/^(?!\.)/u, "./"),
    },
    root: path.resolve(__dirname, "../.."),
  },
  // Your Next.js config here
  webpack: (webpackConfig) => {
    webpackConfig.resolve.extensionAlias = {
      ".cjs": [".cts", ".cjs"],
      ".js": [".ts", ".tsx", ".js", ".jsx"],
      ".mjs": [".mts", ".mjs"],
    };
    webpackConfig.resolve.alias = { ...webpackConfig.resolve.alias, "@ct/legacy-map": LEGACY_MAP };

    return webpackConfig;
  },
  reactCompiler: true,
  transpilePackages: ["@yoast/search-metadata-previews", "@yoast/components"],
  experimental: {
    inlineCss: true,
  },
  images: {
    localPatterns: [{ pathname: "**", search: "" }, { pathname: "/api/media/**" }],
    minimumCacheTTL: THIRTY_DAYS_IN_SECONDS,
    qualities: [75, 85],
    remotePatterns: [{ hostname: "*.public.blob.vercel-storage.com", protocol: "https" }],
  },
};

const withNextIntl = createNextIntlPlugin("./src/lib/i18n/request.ts");

export default withNextIntl(withPayload(nextConfig, { devBundleServerPackages: false }));
