import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "page_blocks_hero" ADD COLUMN "eyebrow" varchar;
  ALTER TABLE "page_blocks_content" ADD COLUMN "description" varchar;
  ALTER TABLE "page_blocks_faq" ADD COLUMN "description" varchar;
  ALTER TABLE "page_blocks_testimonials_list" ADD COLUMN "description" varchar;
  ALTER TABLE "page_blocks_cards_grid" ADD COLUMN "description" varchar;
  ALTER TABLE "page_blocks_carousel" ADD COLUMN "description" varchar;
  ALTER TABLE "page_blocks_chart" ADD COLUMN "description" varchar;
  ALTER TABLE "page_blocks_cta_band" ADD COLUMN "description" varchar;
  ALTER TABLE "page_blocks_newsletter" ADD COLUMN "eyebrow" varchar;
  ALTER TABLE "_page_v_blocks_hero" ADD COLUMN "eyebrow" varchar;
  ALTER TABLE "_page_v_blocks_content" ADD COLUMN "description" varchar;
  ALTER TABLE "_page_v_blocks_faq" ADD COLUMN "description" varchar;
  ALTER TABLE "_page_v_blocks_testimonials_list" ADD COLUMN "description" varchar;
  ALTER TABLE "_page_v_blocks_cards_grid" ADD COLUMN "description" varchar;
  ALTER TABLE "_page_v_blocks_carousel" ADD COLUMN "description" varchar;
  ALTER TABLE "_page_v_blocks_chart" ADD COLUMN "description" varchar;
  ALTER TABLE "_page_v_blocks_cta_band" ADD COLUMN "description" varchar;
  ALTER TABLE "_page_v_blocks_newsletter" ADD COLUMN "eyebrow" varchar;
  ALTER TABLE "posts_locales" ADD COLUMN "cta_eyebrow" varchar;
  ALTER TABLE "_posts_v_locales" ADD COLUMN "version_cta_eyebrow" varchar;
  ALTER TABLE "header_nav_items" ADD COLUMN "dropdown_featured_eyebrow" varchar;
  ALTER TABLE "_header_v_version_nav_items" ADD COLUMN "dropdown_featured_eyebrow" varchar;
  ALTER TABLE "presets_blocks_hero_locales" ADD COLUMN "eyebrow" varchar;
  ALTER TABLE "presets_blocks_content_locales" ADD COLUMN "description" varchar;
  ALTER TABLE "presets_blocks_faq_locales" ADD COLUMN "description" varchar;
  ALTER TABLE "presets_blocks_testimonials_list_locales" ADD COLUMN "description" varchar;
  ALTER TABLE "presets_blocks_cards_grid_locales" ADD COLUMN "description" varchar;
  ALTER TABLE "presets_blocks_carousel_locales" ADD COLUMN "description" varchar;
  ALTER TABLE "presets_blocks_chart_locales" ADD COLUMN "description" varchar;
  ALTER TABLE "presets_blocks_cta_band_locales" ADD COLUMN "description" varchar;
  ALTER TABLE "presets_blocks_newsletter_locales" ADD COLUMN "eyebrow" varchar;
  ALTER TABLE "site_settings_locales" ADD COLUMN "blog_eyebrow" varchar;
  ALTER TABLE "_site_settings_v_locales" ADD COLUMN "version_blog_eyebrow" varchar;
  ALTER TABLE "page_blocks_hero" DROP COLUMN "badge";
  ALTER TABLE "page_blocks_content" DROP COLUMN "lead";
  ALTER TABLE "page_blocks_faq" DROP COLUMN "lead";
  ALTER TABLE "page_blocks_testimonials_list" DROP COLUMN "lead";
  ALTER TABLE "page_blocks_cards_grid" DROP COLUMN "lead";
  ALTER TABLE "page_blocks_carousel" DROP COLUMN "lead";
  ALTER TABLE "page_blocks_chart" DROP COLUMN "lead";
  ALTER TABLE "page_blocks_cta_band" DROP COLUMN "lead";
  ALTER TABLE "page_blocks_newsletter" DROP COLUMN "badge";
  ALTER TABLE "_page_v_blocks_hero" DROP COLUMN "badge";
  ALTER TABLE "_page_v_blocks_content" DROP COLUMN "lead";
  ALTER TABLE "_page_v_blocks_faq" DROP COLUMN "lead";
  ALTER TABLE "_page_v_blocks_testimonials_list" DROP COLUMN "lead";
  ALTER TABLE "_page_v_blocks_cards_grid" DROP COLUMN "lead";
  ALTER TABLE "_page_v_blocks_carousel" DROP COLUMN "lead";
  ALTER TABLE "_page_v_blocks_chart" DROP COLUMN "lead";
  ALTER TABLE "_page_v_blocks_cta_band" DROP COLUMN "lead";
  ALTER TABLE "_page_v_blocks_newsletter" DROP COLUMN "badge";
  ALTER TABLE "posts_locales" DROP COLUMN "cta_badge";
  ALTER TABLE "_posts_v_locales" DROP COLUMN "version_cta_badge";
  ALTER TABLE "header_nav_items" DROP COLUMN "dropdown_featured_badge";
  ALTER TABLE "_header_v_version_nav_items" DROP COLUMN "dropdown_featured_badge";
  ALTER TABLE "presets_blocks_hero_locales" DROP COLUMN "badge";
  ALTER TABLE "presets_blocks_content_locales" DROP COLUMN "lead";
  ALTER TABLE "presets_blocks_faq_locales" DROP COLUMN "lead";
  ALTER TABLE "presets_blocks_testimonials_list_locales" DROP COLUMN "lead";
  ALTER TABLE "presets_blocks_cards_grid_locales" DROP COLUMN "lead";
  ALTER TABLE "presets_blocks_carousel_locales" DROP COLUMN "lead";
  ALTER TABLE "presets_blocks_chart_locales" DROP COLUMN "lead";
  ALTER TABLE "presets_blocks_cta_band_locales" DROP COLUMN "lead";
  ALTER TABLE "presets_blocks_newsletter_locales" DROP COLUMN "badge";
  ALTER TABLE "site_settings_locales" DROP COLUMN "blog_blog_badge";
  ALTER TABLE "_site_settings_v_locales" DROP COLUMN "version_blog_blog_badge";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "page_blocks_hero" ADD COLUMN "badge" varchar;
  ALTER TABLE "page_blocks_content" ADD COLUMN "lead" varchar;
  ALTER TABLE "page_blocks_faq" ADD COLUMN "lead" varchar;
  ALTER TABLE "page_blocks_testimonials_list" ADD COLUMN "lead" varchar;
  ALTER TABLE "page_blocks_cards_grid" ADD COLUMN "lead" varchar;
  ALTER TABLE "page_blocks_carousel" ADD COLUMN "lead" varchar;
  ALTER TABLE "page_blocks_chart" ADD COLUMN "lead" varchar;
  ALTER TABLE "page_blocks_cta_band" ADD COLUMN "lead" varchar;
  ALTER TABLE "page_blocks_newsletter" ADD COLUMN "badge" varchar;
  ALTER TABLE "_page_v_blocks_hero" ADD COLUMN "badge" varchar;
  ALTER TABLE "_page_v_blocks_content" ADD COLUMN "lead" varchar;
  ALTER TABLE "_page_v_blocks_faq" ADD COLUMN "lead" varchar;
  ALTER TABLE "_page_v_blocks_testimonials_list" ADD COLUMN "lead" varchar;
  ALTER TABLE "_page_v_blocks_cards_grid" ADD COLUMN "lead" varchar;
  ALTER TABLE "_page_v_blocks_carousel" ADD COLUMN "lead" varchar;
  ALTER TABLE "_page_v_blocks_chart" ADD COLUMN "lead" varchar;
  ALTER TABLE "_page_v_blocks_cta_band" ADD COLUMN "lead" varchar;
  ALTER TABLE "_page_v_blocks_newsletter" ADD COLUMN "badge" varchar;
  ALTER TABLE "posts_locales" ADD COLUMN "cta_badge" varchar;
  ALTER TABLE "_posts_v_locales" ADD COLUMN "version_cta_badge" varchar;
  ALTER TABLE "header_nav_items" ADD COLUMN "dropdown_featured_badge" varchar;
  ALTER TABLE "_header_v_version_nav_items" ADD COLUMN "dropdown_featured_badge" varchar;
  ALTER TABLE "presets_blocks_hero_locales" ADD COLUMN "badge" varchar;
  ALTER TABLE "presets_blocks_content_locales" ADD COLUMN "lead" varchar;
  ALTER TABLE "presets_blocks_faq_locales" ADD COLUMN "lead" varchar;
  ALTER TABLE "presets_blocks_testimonials_list_locales" ADD COLUMN "lead" varchar;
  ALTER TABLE "presets_blocks_cards_grid_locales" ADD COLUMN "lead" varchar;
  ALTER TABLE "presets_blocks_carousel_locales" ADD COLUMN "lead" varchar;
  ALTER TABLE "presets_blocks_chart_locales" ADD COLUMN "lead" varchar;
  ALTER TABLE "presets_blocks_cta_band_locales" ADD COLUMN "lead" varchar;
  ALTER TABLE "presets_blocks_newsletter_locales" ADD COLUMN "badge" varchar;
  ALTER TABLE "site_settings_locales" ADD COLUMN "blog_blog_badge" varchar;
  ALTER TABLE "_site_settings_v_locales" ADD COLUMN "version_blog_blog_badge" varchar;
  ALTER TABLE "page_blocks_hero" DROP COLUMN "eyebrow";
  ALTER TABLE "page_blocks_content" DROP COLUMN "description";
  ALTER TABLE "page_blocks_faq" DROP COLUMN "description";
  ALTER TABLE "page_blocks_testimonials_list" DROP COLUMN "description";
  ALTER TABLE "page_blocks_cards_grid" DROP COLUMN "description";
  ALTER TABLE "page_blocks_carousel" DROP COLUMN "description";
  ALTER TABLE "page_blocks_chart" DROP COLUMN "description";
  ALTER TABLE "page_blocks_cta_band" DROP COLUMN "description";
  ALTER TABLE "page_blocks_newsletter" DROP COLUMN "eyebrow";
  ALTER TABLE "_page_v_blocks_hero" DROP COLUMN "eyebrow";
  ALTER TABLE "_page_v_blocks_content" DROP COLUMN "description";
  ALTER TABLE "_page_v_blocks_faq" DROP COLUMN "description";
  ALTER TABLE "_page_v_blocks_testimonials_list" DROP COLUMN "description";
  ALTER TABLE "_page_v_blocks_cards_grid" DROP COLUMN "description";
  ALTER TABLE "_page_v_blocks_carousel" DROP COLUMN "description";
  ALTER TABLE "_page_v_blocks_chart" DROP COLUMN "description";
  ALTER TABLE "_page_v_blocks_cta_band" DROP COLUMN "description";
  ALTER TABLE "_page_v_blocks_newsletter" DROP COLUMN "eyebrow";
  ALTER TABLE "posts_locales" DROP COLUMN "cta_eyebrow";
  ALTER TABLE "_posts_v_locales" DROP COLUMN "version_cta_eyebrow";
  ALTER TABLE "header_nav_items" DROP COLUMN "dropdown_featured_eyebrow";
  ALTER TABLE "_header_v_version_nav_items" DROP COLUMN "dropdown_featured_eyebrow";
  ALTER TABLE "presets_blocks_hero_locales" DROP COLUMN "eyebrow";
  ALTER TABLE "presets_blocks_content_locales" DROP COLUMN "description";
  ALTER TABLE "presets_blocks_faq_locales" DROP COLUMN "description";
  ALTER TABLE "presets_blocks_testimonials_list_locales" DROP COLUMN "description";
  ALTER TABLE "presets_blocks_cards_grid_locales" DROP COLUMN "description";
  ALTER TABLE "presets_blocks_carousel_locales" DROP COLUMN "description";
  ALTER TABLE "presets_blocks_chart_locales" DROP COLUMN "description";
  ALTER TABLE "presets_blocks_cta_band_locales" DROP COLUMN "description";
  ALTER TABLE "presets_blocks_newsletter_locales" DROP COLUMN "eyebrow";
  ALTER TABLE "site_settings_locales" DROP COLUMN "blog_eyebrow";
  ALTER TABLE "_site_settings_v_locales" DROP COLUMN "version_blog_eyebrow";`)
}
