// The frame files are served by the plugin's own endpoint rather than from the app's `public/`, so
// they are compiled into the package as strings — nothing to copy, nothing for a bundler to trace.
import { readFileSync, writeFileSync } from "node:fs";

const dir = new URL("../src/frame/", import.meta.url);
const files = {
  "click-to-edit.js": "text/javascript; charset=utf-8",
  "unsaved-edits.js": "text/javascript; charset=utf-8",
  "frame.css": "text/css; charset=utf-8",
};

const entries = Object.entries(files).map(
  ([name, type]) =>
    `\t${JSON.stringify(name)}: { type: ${JSON.stringify(type)}, body: ${JSON.stringify(readFileSync(new URL(name, dir), "utf-8"))} },`
);
writeFileSync(
  new URL("assets.ts", dir),
  `// Generated by scripts/embed-frame.mjs from the files next to it — edit those, not this.\nexport const FRAME_ASSETS: Record<string, { type: string; body: string }> = {\n${entries.join("\n")}\n};\n`
);
